### ISSUE TITLE
Missing arg to train.sh in finetune_teacher (Snakefile)?

### ISSUE THREAD

**Issue by hobodrifterdavid** [mozilla/firefox-translations-training#105]
Hit this error when running make test (local profile, Ubuntu 20.04):

![image](https://user-images.githubusercontent.com/16459990/210579994-9b2cdee2-73e7-4a47-af25-7681ee3237b4.png)

Comparing to other places train.sh is run, looks like this is missing:
![image](https://user-images.githubusercontent.com/16459990/210582945-df21c72f-8edf-4823-a608-fd2920d4dc46.png)

Script runs now..

**Comment by eu9ene** [comment]
@AmitMY I think you missed this one here https://github.com/mozilla/firefox-translations-training/pull/103

**Comment by AmitMY** [comment]
Thanks for picking up on that! fixed in PR
