### ISSUE TITLE
Any roadmap for firefox-translations-training?

### ISSUE THREAD

**Issue by TommiNieminen** [mozilla/firefox-translations-training#116]
I am working on an MT project at the University of Helsinki, and I'm using _firefox-translations-training_ as the basis for our training pipeline (it's very convenient to use, thanks for developing it). I am adding some functionalities to the pipeline to support our research, the main addition I have made so far is the possibility of using OPUS-MT models as teachers in the pipeline (you can find the code here: https://github.com/GreenNLP/firefox-translations-training).

I'd be interested to know if you have any plans on extending _firefox-translations-training_, so that I can avoid duplicated effort. I see you are currently working on Taskcluster support, are there plans for other updates?

**Comment by andrenatal** [comment]
Hi @TommiNieminen. Thanks for reaching out. Yes, this is something I was planning to do. I saw many OPUS-MT models posted to HuggingFace and considered using them as teachers. Could you push a PR here so we can collaborate on that? 

We plan to use Taskcluster to make it easier to spin multiple training jobs simultaneously, and it would be fantastic if we could leverage these pre-trained teachers to allow us to scale to much more languages faster and in parallel. I'm open to have a call if you are interested. 

Thanks!

**Comment by TommiNieminen** [comment]
Hi @andrenatal,

I just pushed a draft PR for the changes. Of course, the changes are mostly in the Snakefile, so they would still have to be ported to your new Taskcluster setup.

It would be great if you can use OPUS-MT models in your workflow. It would also be a good fit for our GreenNLP project, since part of its mission is to promote the reuse of NLP models. Should we have a Zoom call to discuss this further?

-Tommi
