### ISSUE TITLE
Issues with casing

### ISSUE THREAD

**Issue by marco-c** [mozilla/firefox-translations-training#129]
Example: https://github.com/mozilla/firefox-translations/issues/716.

"QUELS COOKIES ET QUELS TRACEURS ?" is translated as "WHAT COOKIES AND THAT THAT THAT THAT COOKING AND THAT COOKIES AND TH ".
"Quels cookies et quels traceurs ?" is translated as "What cookies and tracers? ". Same if we lowercase only a subset of the initial sentence.

**Comment by marco-c** [comment]
Duplicate of #73.

**Comment by marco-c** [comment]
Actually, there are other issues with casing, such as https://github.com/mozilla/firefox-translations/issues/681 (where the translation is good for "to whet your appetite" but bad for "To whet your appetite"). I'll reopen this, and we can track in #73 the ALL CAPS case.

**Comment by marco-c** [comment]
@eu9ene does the TitleCase augmentation fix this class of problems?

**Comment by eu9ene** [comment]
UpperCase/TitleCase augmentations are supposed to fix the problems related to casing, but we still need to test the final model in Nightly to verify.

**Comment by eu9ene** [comment]
Yes, title case augmentation is supposed to take care of the example you posted.
