### ISSUE TITLE
Implement pretrained backwards models in Taskcluster

### ISSUE THREAD

**Issue by bhearsum** [mozilla/firefox-translations-training#141]
At the moment, Taskcluster can only find a backwards model that it trained itself. We need to be able to override or otherwise specify a source for pretrained backwards models. I suggest that we allow for this in at least two ways:
- Telling Taskcluster to use a specific Taskcluster task instead of generating a new one
- Telling Taskcluster to pull a pretrained backwards model & decoder config from an URL. (I would suggest that we specifically require them to be in a zip file, tarball, or whatever to avoid pain if we need additional files in the future.)

In either case, specifying one of these should result in no tasks being scheduled for `train-backwards` or any of its dependencies that aren't needed by other tasks not being skipped.

We have a placeholder for this [in the parameters](https://github.com/mozilla/firefox-translations-training/blob/c2f7357dc96d7071ad5d18784e754ffd4a9a6c03/taskcluster/translations_taskgraph/actions/train.py#L63) and [action inputs](https://github.com/mozilla/firefox-translations-training/blob/c2f7357dc96d7071ad5d18784e754ffd4a9a6c03/taskcluster/translations_taskgraph/parameters.py#L22).

Some thoughts on how to implement this:
- In the case of an external backwards model, we should generate a fetch task that pulls it.
- In both cases (external + specified task) we should replace the regularly generated `train-backwards` step in [an Optimization](https://taskcluster-taskgraph.readthedocs.io/en/latest/concepts/optimization.html) (either with the fetch task above, or the task that was specified in the parameters). We may need to do a small amount of extra work to find and remove any tasks that the regular `train-backwards` step depends on (I don't think removing it in optimization will automatically remove these - but maybe I'm wrong).

It would be beneficial to try to implement this in a re-usable way - there are many other parts of the pipeline we'd like to be able to do this with (teachers, vocab, etc.).

**Comment by eu9ene** [comment]
This will be implemented as a part of training continuation #154
