### ISSUE TITLE
Implement pretrained vocab in Taskcluster

### ISSUE THREAD

**Issue by bhearsum** [mozilla/firefox-translations-training#142]
This is the same as #141, but for vocab. We have [placeholders for this](https://github.com/mozilla/firefox-translations-training/blob/c2f7357dc96d7071ad5d18784e754ffd4a9a6c03/taskcluster/translations_taskgraph/actions/train.py#L67).

**Comment by eu9ene** [comment]
This will be implemented as a part of training continuation #154
