### ISSUE TITLE
Add support for public custom corpus' in Taskcluster

### ISSUE THREAD

**Issue by bhearsum** [mozilla/firefox-translations-training#143]
The Snakemake pipeline has support for using "custom" corpus' - that is, datasets that are not available through an URL. As I understand it, these work by someone creating the dataset with a specific name somewhere in the Berlin cluster, which is then referenced in the pipeline config.

I think our best bet for doing this would be to set-up a GCP bucket to hold the custom corpus' and add a new importer that knows how to fetch from it. The new importer would receive the bucket name (or possibly URL) in addition to the usual src/trg/output_prefix/dataset. We'd specify these datasets with strings like "custom-gcp_dataset-name". The bucket would be configured in `ci/config.yml`.

This would also allow us to train against private datasets (eg: things that we purchase that cannot be redistributed publicly).

**Comment by gabrielBusta** [comment]
Seems related to https://github.com/mozilla/firefox-translations-training/issues/191

I get the feeling we should get a bucket for translations?

**Comment by eu9ene** [comment]
Yes, we should create a public bucket for translations where we can store old models for fine-tuning and public custom datasets (that are not available on OPUS or mtdata). I don't know about the archive of the jobs, the requirements for visibility of this one and the retention policy might be different, so I would put it in a separate bucket.

We will need the customer importer to work soon to train English to Catalan cc @gregtatum
