### ISSUE TITLE
Show config validation error

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#155]
When the config is invalid, it looks like this:

<img width="1467" alt="Screenshot 2023-08-01 at 2 54 18 PM" src="https://github.com/mozilla/firefox-translations-training/assets/2486505/5549daaa-4e4d-48ca-ba08-83b352f15055">

We should add a readable error that explains what's wrong.

**Comment by gabrielBusta** [comment]
This was filed as https://github.com/taskcluster/taskcluster/issues/6720

I landed a fix https://github.com/taskcluster/taskcluster/pull/6772

It seems to be working now. I tried it out:

<img width="1889" alt="Screenshot 2024-01-26 at 14 43 42" src="https://github.com/mozilla/firefox-translations-training/assets/10228658/15e10f5c-4c14-4ad5-9e5f-6efbc32ea8b4">
