### ISSUE TITLE
Add live logs for all tasks

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#156]
I noticed that there are no live logs for a training task. We need to look at live logs for all tasks, especially training ones to monitor training progress and make decisions about aborting or continuation or identifying that the task is stuck.

**Comment by hwine** [comment]
**Note:** we don't normally provide livelog access to L3 workers, so we have to do a bit of research here to ensure it's done securely.

**Comment by gregtatum** [comment]
I agree that this is a blocker.

**Comment by gabrielBusta** [comment]
These are working now https://phabricator.services.mozilla.com/D186832
