### ISSUE TITLE
Remove retries for all tasks except the ones that depend on external resources

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#157]
If the task is broken and expensive to run, the current 5 retries make the cost of failing even higher. For example, if something is broken in training and we can see it in the logs from the first attempt, we don't really want to run automatic retries. I think the only use case when it might be useful is in those places where we call external API that might be temporarily unavailable, for example, dataset downloading. Even for those, I think a couple of retries with a time interval should be enough. Otherwise, we just delay the notification of failing. Let's discuss.

**Comment by gregtatum** [comment]
It seems reasonable to be able to control this and fine-tune it for our tasks. I created a new "cost & perf" label.

**Comment by eu9ene** [comment]
We can disable all retries for now

**Comment by eu9ene** [comment]
It turns out automatic retries run only for infrastructure issues and require manual specification of `retry-exit-status` which is what we want.
