### ISSUE TITLE
Integrate OpusCleaner

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#160]
[OpusCleaner](https://github.com/hplt-project/OpusCleaner) is a new data-cleaning tool developed as a part of the [HPLT](https://hplt-project.org/) project.

This tool can help us customize cleaning for different languages and datasets, provide a convenient UI and a way to store cleaning configs. Also, we'll be in sync with the latest developments in the HPLT.

I assume we can implement the following workflow: 
1. Use the UI to develop the cleaning configs
2. Host configs in this repo or in some other place to share with HPLT project
3. Keep our current dataset downloading procedures
4. Use the [standalone cleaning script](https://github.com/hplt-project/OpusCleaner/blob/main/opuscleaner/clean.py) provided by OpusCleaner in the cleaning step of the pipeline instead of the current scripts

**Questions:**
1. Is OpusCleaner stable enough to start integration? Is it already being actively used? It looks like it's under active development
2. Creating a custom cleaning config for each language and dataset is challenging, especially if you don't know the language. Should we have a hierarchy of default configs, for example, defaults for all, defaults for a language, and defaults for a dataset? 
3. Where to store the configs and what are the plans of the developers of HPLT for this? At some point we might want to develop guidelines on how to use the tool and accept community contributions.

**Comment by eu9ene** [comment]
@kpu @XapaJIaMnu @jelmervdl I'm curious what are your thoughts on this. Maybe you can answer some of my questions and provide some insights for this project. Thanks!

**Comment by XapaJIaMnu** [comment]
Hi,
Sorry for the late reply!
> Is OpusCleaner stable enough to start integration? Is it already being actively used? It looks like it's under active development.
We have already used OpusCleaner to build a number of models, so it is "usable" but it is also under active development. It lacks a few features (notably `bicleaner-ai`, which should be used for the really dirty datasets, and post filtering deduplicator).

> Creating a custom cleaning config for each language and dataset is challenging, especially if you don't know the language. Should we have a hierarchy of default configs, for example, defaults for all, defaults for a language, and defaults for a dataset?

Yes we should have defaults but we haven't produced any yet. I have produced a replicator that will replicate a config for all datasets, which sort of functions as default. https://github.com/hplt-project/OpusCleaner/issues/37#issuecomment-1669981108

> Where to store the configs and what are the plans of the developers of HPLT for this? At some point we might want to develop guidelines on how to use the tool and accept community contributions.
The idea is that we will store example configs to "clean"-ish datasets and "dirty"-ish datasets for each language pair and users can build on top of that. However we have not gotten to that point yet.

**Comment by eu9ene** [comment]
Hi @XapaJIaMnu! Thank you for the reply, I'm glad to see you working on this! :)

> Yes we should have defaults but we haven't produced any yet. I have produced a replicator that will replicate a config for all datasets, which sort of functions as default. https://github.com/hplt-project/OpusCleaner/issues/37#issuecomment-1669981108

Ok, I filed some issues in OpusCleaner, notably https://github.com/hplt-project/OpusCleaner/issues/101. I understand that it might not be exactly the architecture you had in mind. I'll need to work around it on my side for now.

As a first pass, I'll try to reproduce our current cleaning rules using OpusCleaner as the default ones with the ability to override them with the dataset-specific filters produced by the UI. If a specific config is absent, I'll generate it on the fly using the defaults in the format expected by `opuscleaner-clean` with something like this tool https://github.com/hplt-project/OpusCleaner/issues/37#issuecomment-1669981108.

**Comment by gregtatum** [comment]
> configs in this repo or in some other place

I would prefer to have the configs in this repo, that way we maintain one source of truth. We could pull in configs from external places as needed. The way I look at it, the more declarative we can be in our configuration the better.
