### ISSUE TITLE
Some words should be passing through untranslated (e.g. IPA characters, emojis, etc.)

### ISSUE THREAD

**Issue by marco-c** [mozilla/firefox-translations-training#171]
See also:
https://github.com/mozilla/firefox-translations/issues/365
https://github.com/browsermt/bergamot-translator/issues/185
https://github.com/browsermt/bergamot-translator/issues/419
https://github.com/mozilla/firefox-translations/issues/514
https://github.com/mozilla/firefox-translations/issues/511
https://github.com/mozilla/firefox-translations/issues/442
https://github.com/mozilla/firefox-translations/issues/375
https://bugzilla.mozilla.org/show_bug.cgi?id=1862017

**Comment by eu9ene** [comment]
And also links, see https://bugzilla.mozilla.org/show_bug.cgi?id=1862017

![image](https://github.com/mozilla/firefox-translations-training/assets/2486505/a8117734-8189-43a9-aab9-f13b9139dcb8)

**Comment by eu9ene** [comment]
Add support for the OpusTrainer Tags modifier.

It might require training alignments based on space tokenization instead of sentencepiece one. See[ this issue](https://github.com/hplt-project/OpusTrainer/issues/38).

**Comment by marco-c** [comment]
@eu9ene is this fixed by the inline noise augmentation? Does it cover all cases mentioned in the first comment?

**Comment by eu9ene** [comment]
I'm still training students with inline noise. We'll need to test all these cases with the final model, ideally in Nightly to say that they were fixed.

**Comment by eu9ene** [comment]
Noise/inline noise augmentations are supposed to take care of most of those cases but we'll need to verify it all in the wild when the quantized models arrive.
