### ISSUE TITLE
 Improve translation of sentences containing numbers

### ISSUE THREAD

**Issue by marco-c** [mozilla/firefox-translations-training#173]
See also https://github.com/mozilla/firefox-translations/issues/534 and https://bugzilla.mozilla.org/show_bug.cgi?id=1842763 and https://bugzilla.mozilla.org/show_bug.cgi?id=1842765.

**Comment by eu9ene** [comment]
Better data cleaning should help (remove sentences from the training datasets that present this problem, or “clean” them to make the numbers match in original/translated)

**Comment by eu9ene** [comment]
This is supposed to be handled by the OpusCleaner `num_mismatch` filter which removes any lines with non-matching numbers pretty aggressively. It is a part of the production training pipeline now. Again we'll need to retest this in the wild when quantized student models arrive.

**Comment by eu9ene** [comment]
I don't know if we handled all of the specified cases though. If we see some of it with the new models, we can create new separate issues.
