### ISSUE TITLE
Add comparisons with teacher models

### ISSUE THREAD

**Issue by marco-c** [mozilla/firefox-translations-training#175]
In our evaluation code, we currently compare our student models against models from other vendors.
We should add our teacher models to the comparison, so we can know how much quality we are losing when distilling.
This will help figure out if #174 is worth it or not.

**Comment by eu9ene** [comment]
We have this info on disk and it's easy to check. I expect #14 to solve the visibility issue.

**Comment by eu9ene** [comment]
We have a comparison across all the models in W&B now.  When we land #503 it will be even easier to compare with prod models. I think the epic of merging the evaluation pipeline into this repo is out of scope for this issue, so closing for now.
