### ISSUE TITLE
Ensure random whitespaces between characters don't trigger wrong translations

### ISSUE THREAD

**Issue by marco-c** [mozilla/firefox-translations-training#176]
E.g. `Chute de la Silicon Valley Bank : les leçons d’une faillite bancaire` translates badly, `Chute de la Silicon Valley Bank: les leçons d’une faillite bancaire` translates correctly.

This might be an issue related to tokenization (see also https://github.com/google/sentencepiece#whitespace-is-treated-as-a-basic-symbol).

See also https://github.com/mozilla/firefox-translations/issues/688.

**Comment by eu9ene** [comment]
Typos augmentation is supposed to handle this. Let's reopen if it's still present.
