### ISSUE TITLE
Evaluate translation capabilities of LLMs

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#186]
If practical, the LLMs might be useful for a variety of tasks:
- Quality evaluation
- Data augmentation (including back translation for low-resource languages)
- Using as a teacher model

As a first step,  we can translate test datasets for some languages we support and calculate metrics to understand where the models stand.

We should also measure the speed of translation to understand whether it will be practical at all to use LLMs (translating millions of sentences for augmentation might be too slow for example)

We can look at:
- OpenAI GPT4
- OpenAI GPT3.5
- Llama2 13B
- Llama2 7B
+ Quantized versions (8bit, 4bit) if llama is too slow

We can also take a look at specialized multilingual models with permissive licences.

There is also this paper with some benchmarks https://arxiv.org/pdf/2302.09210.pdf but it's old and checks only GPT3.5

**Comment by eu9ene** [comment]
@marco-c FYI since you already started some work on this

**Comment by ishaan-jaff** [comment]
Hi @eu9ene @marco-c  if you're still trying to benchmark / eval llms 

I'm the maintainer of LiteLLM. **I believe LiteLLM makes it easier for you to run benchmarks and evaluate LLMs (I'd love your feedback if it does not)**

Try it here: https://docs.litellm.ai/docs/simple_proxy
https://github.com/BerriAI/litellm

## Using LiteLLM Proxy Server
## Creating a proxy server 
Ollama models
```shell
$ litellm --model ollama/llama2 --api_base http://localhost:11434
```

Hugging Face Models 
```shell
$ export HUGGINGFACE_API_KEY=my-api-key #[OPTIONAL]
$ litellm --model claude-instant-1
```

Anthropic 
```shell
$ export ANTHROPIC_API_KEY=my-api-key
$ litellm --model claude-instant-1
```
Palm

```shell
$ export PALM_API_KEY=my-palm-key
$ litellm --model palm/chat-bison
```

## Set api base to proxy
```
openai.api_base = "http://0.0.0.0:8000"
```

## Using to run an eval on lm harness:
```python
python3 -m lm_eval \
  --model openai-completions \
  --model_args engine=davinci \
  --task crows_pairs_english_age

```

**Comment by marco-c** [comment]
Another area where this could be useful is helping us defining cleaning rules for datasets.

**Comment by marco-c** [comment]
See also https://arxiv.org/pdf/2302.14520.pdf.

**Comment by eu9ene** [comment]
> See also https://arxiv.org/pdf/2302.14520.pdf.

This one is on my list :) 

["A PARADIGM SHIFT IN MACHINE TRANSLATION: BOOSTING TRANSLATION PERFORMANCE OF LARGE LANGUAGE MODELS"](https://arxiv.org/pdf/2309.11674.pdf) is another interesting one

**Comment by eu9ene** [comment]
WMT23: https://aclanthology.org/2023.wmt-1.1.pdf

**Comment by eu9ene** [comment]
I analyzed the results of https://arxiv.org/pdf/2302.09210.pdf  and https://arxiv.org/pdf/2309.11674.pdf and also benchmarked [ALMA-13B-LoRA ](https://huggingface.co/haoranxu/ALMA-13B)myself. The quality is pretty good and looks on par with Google API for xx-en and slightly worse for en-xx:

<img width="1587" alt="Screenshot 2024-07-16 at 2 41 42 PM" src="https://github.com/user-attachments/assets/95ed247e-4839-49bb-81b2-ea0797a936de">

The main problem from a practical perspective is inference cost (for the API) and speed (for the fine-tuned llama-2 13B). Most of our pipelines (cleaning, decoding etc.) work on hundreds of millions of parallel sentences. The inference speed on 8 x q6000 (24GB) was 13 sec per batch of 10 sentences. I played a bit with the batch size but couldn't get significantly better results.

I guess it's possible to optimize further but it seems it's practical to use LLMs only for the tasks that are limited to small samples, for example, analysis of evaluation or tuning thresholds for cleaning and similar.

**Comment by gregtatum** [comment]
@eu9ene Can you link to the spreadsheet? Seems like something we could share publicly.

**Comment by gregtatum** [comment]
Doing some quick estimates based on your numbers.

Sentence Count | Hours to Train | $1/hr GPU | $5/hr GPU
-- | -- | -- | --
1,000,000 | 21.37 | $21.37 | $106.84
10,000,000 | 213.68 | $213.68 | $1,068.38
100,000,000 | 2136.75 | $2,136.75 | $10,683.76

**Comment by eu9ene** [comment]
Sure, [here](https://docs.google.com/spreadsheets/d/1O77Ap0zA5xMw0gbzfLBDPLKaM2zAAVgFeN8TF227fbg/edit?usp=sharing) it is but that's basically it. I wanted to also benchmark for WM23 but didn't have time for it.

For the out-of-the-envelope calculations: for [this mono task](https://firefox-ci-tc.services.mozilla.com/tasks/K1wuw2XQRPu4SfwJyWf5mQ/runs/0/logs/public/logs/live.log) we translated 13143105 lines in 197969 seconds = 66 lines per second. It was performed on V100 x 4 which is roughly equivalent to q6000 x 8 in practice. So for this 13B LLM it would be 1 line/sec which is almost two orders of magnitude lower, especially if we'll be able to further optimize inference with CTranslate.

**Comment by eu9ene** [comment]
The empty cells for some languages are where the model failed to follow the prompt and translate all the examples, so like with all other LLM tasks it's not 100% reliable.

**Comment by eu9ene** [comment]
Here's the code I used if you're interested. It utilizes all 8 GPUs (not on 100% though) and allocates 20GB of GPU memory for each GPU. There are ways to run faster for example with [vLLM](https://blog.vllm.ai/2023/06/20/vllm.html) but it won't change things dramatically since the model has 67 times more parameters than our teacher.
