### ISSUE TITLE
Requirements for the python venv

### ISSUE THREAD

**Issue by kirianguiller** [mozilla/firefox-translations-training#2]
Hi everyone, thanks for this nice repo :).

I wanted to know if it's possible to share the requirements needed for the loval python (conda) venv that is [sourced here](https://github.com/mozilla/firefox-translations-training/blob/af2abbf5254695132580a8cd4b92b9f7cc13c431/run.sh#L64) ? I would help for reproducibility. Fasttext is being used in [this script](https://github.com/mozilla/firefox-translations-training/blob/main/pipeline/clean/tools/langid_fasttext.py), which mean at least one non built-in python module is required.

Thanks :)

**Comment by eu9ene** [comment]
Hi @kirianguiller, python requirements are specified [here](https://github.com/mozilla/firefox-translations-training/blob/main/pipeline/setup/requirements.txt) and installed in python setup [script](https://github.com/mozilla/firefox-translations-training/blob/main/pipeline/setup/install-python.sh).

**Comment by kirianguiller** [comment]
Top :). I'm closing the issue then. Thanks !
