### ISSUE TITLE
Out of memory on shuffling huge datasets

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#21]
300M dataset, 128 GB RAM

the workaround is to shuffle dataset after the merge step, disable `--shuffle-in-ram` and use `--shuffle batches`

**Comment by eu9ene** [comment]
This might be a bug of Marian. Memory shouldn't grow after `--shuffle-in-ram` is removed and we should use `--shuffle data` mode. It was discussed in https://github.com/mozilla/firefox-translations-training/pull/70#discussion_r800975032

**Comment by eu9ene** [comment]
Training teachers with `--shuffle batches` leads to such training curves. Maybe other factors are at play here.
<img width="351" alt="Screen Shot 2022-06-10 at 12 40 14 PM" src="https://user-images.githubusercontent.com/2486505/173138550-f474498f-c95a-405a-be20-0ce1bc4edf35.png">

**Comment by eu9ene** [comment]
Related Marian issue: https://github.com/marian-nmt/marian-dev/issues/148

**Comment by XapaJIaMnu** [comment]
`--sqlite` should help but I've found it slow in practise.

**Comment by jelmervdl** [comment]
I suspect the running out of memory, even when --shuffle-in-ram is _not_ used, comes from here:

https://github.com/marian-nmt/marian-dev/blob/042ed8f2e23557d0cdb956aea7d79be8c817e0b0/src/data/corpus.cpp#L227-L241

Assuming that's actually the cause, we could replace it with a two-pass shuffle:
1. Read the unshuffled dataset, and write each line to one of N temp files, chosen randomly for each line. 
  How large N needs to be can probably be determined by looking at how large the input file is, and how much memory is available for shuffling. Might be trickier to estimate if the input file is gzipped.
2. Shuffle each of the temp files as is done now:  
  read it into memory, do `std::shuffle`.
3. Concatenate temp files into the shuffled temp files.  
  Or implement some reader class that takes ownership and reads from the bunch of temp files consecutively as if it were one.

**Comment by eu9ene** [comment]
I didn't see this for some time and I assume it's fixed by using OpusTrainer.
