### ISSUE TITLE
Training Continuation - Use Opus models

### ISSUE THREAD

**Issue by gabrielBusta** [mozilla/firefox-translations-training#213]

**Comment by eu9ene** [comment]
This one requires landing https://github.com/mozilla/firefox-translations-training/pull/192 and then integrating it in the TaskCluster pipeline (the PR covers only Snakemake).

**Comment by gabrielBusta** [comment]
@eu9ene I was trying out the task list thing that's beta, but I kind of feel like it's just going to split the communication plus we have the doc :) so I closed these sub-issues
