### ISSUE TITLE
Add an ability to run starting from a specific task

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#227]
We already have the `target-stage` setting which is convenient to specify where to finish. We should also add an option to specify where to start. It would speed up debugging on Taskculster a lot. Even if the caches work properly we might want to debug the later stages of the pipeline without rerunning the earlier ones, even if the upstream scripts have changed.

**Comment by eu9ene** [comment]
We also discussed that another workaround for faster debugging can be starting an interactive task. I'll try it but since we don't have a persistent disk attached, I think it will be convenient only to test some small modifications or inspect datasets.  So having an option to start from a specific task is still needed.

**Comment by bhearsum** [comment]
@gabrielBusta suggested that this _might_ be able to work similarly to what we do for Firefox release automation, where we feed in `previous_graph_ids` and `rebuild_kinds`. Any tasks not in `rebuild_kinds` are force rebuilt, and any needed tasks found in any of the listed graph ids are used. I'm not _certain_ whether that bypasses caches or not, but we may be able to make that happen regardless.

References:
* https://searchfox.org/mozilla-central/source/taskcluster/docs/release-promotion-action.rst
* https://searchfox.org/mozilla-central/source/taskcluster/gecko_taskgraph/actions/release_promotion.py#136
* https://searchfox.org/mozilla-central/rev/a9cb8b07d4cf4290e693bc31ba23412d0f042cb8/taskcluster/gecko_taskgraph/util/taskgraph.py#33

**Comment by bhearsum** [comment]
Another idea might be to have routes for "latest" for a given language pair so we can easily find a usable set of artifacts. I'll do some more thinking about this.

**Comment by gabrielBusta** [comment]
Another idea to reduce the time it takes to run a task that's deep in the graph is fowarding the `existing_tasks` parameter to the decision created by the action.

Maybe we can forward the parameter from the action's input to the decision like this:

https://github.com/mozilla/firefox-translations-training/blob/fec1fe0669240a72b76688136d129b02a12cddba/taskcluster/translations_taskgraph/actions/train.py#L347-L350

We could then look at decisions that created tasks we want to re-use and grab their [label-to-taskid.json](https://firefoxci.taskcluster-artifacts.net/SACNPLCkRwWjEaCUbMxI8w/0/public/label-to-taskid.json) and use that as the value for `existing_tasks` (minus the task(s) we want to schedule/run repeatedly.)
