### ISSUE TITLE
Pipeline does not respect TMPDIR

### ISSUE THREAD

**Issue by AmitMY** [mozilla/firefox-translations-training#242]
(I am attempting running this repository on the University of Zurich slurm cluster)

Running 
```bash
make run PROFILE=slurm-s3it CONFIG=configs/config.test.yml
```

I get the following log
```
Building DAG of jobs...
Creating conda environment envs/bicleaner.yml...
Downloading and installing remote packages.
```

Then the error:
```
CreateCondaEnvironmentException:
Could not create conda environment from /home/amoryo/sign-language/signbank-annotation/signbank-plus/signbank_plus/nmt/bergamot/firefox-translations-training/envs/bicleaner.yml:
INFO:    Converting SIF file to temporary sandbox...
ERROR   Could not write to file /tmp/mambafN6pKhyCt59: No space left on device
INFO:    Cleaning up image...
```

This seems to be because on the s3it slurm cluster, I am not allowed to write to `/tmp`. 
I tried setting the `TMPDIR` environment variable, but it is not respected, and still attempts to write to `/tmp`

Any chance to respect this environment variable?

**Comment by eu9ene** [comment]
I'm not sure why Snakemake doesn't respect the tempdir. Please refer to Snakemake docs and the Github repo for this. I found a similar [issue](https://github.com/snakemake/snakemake/issues/1003) there.

You can try updating Snakemake to the latest version. It's already done in [GreenNLP fork](https://github.com/GreenNLP/firefox-translations-training) so you might want to give it a try as well. 

We're currently focusing on stabilizing Taskcluster integration, so Snakemake issues will likely be a lower priority.

**Comment by AmitMY** [comment]
I was setting my env variable, not `export`ed. fixed.
