### ISSUE TITLE
quantize: Core Dumped when vocab size *not* a multiple of 8

### ISSUE THREAD

**Issue by AmitMY** [mozilla/firefox-translations-training#249]
```bash
cat /data/logs/spoken-signed/spoken_to_signed/quntize.log
```

```log
+ set -euo pipefail
echo '###### Quantizing a model'
###### Quantizing a model
+ test -v BMT_MARIAN
+ test -v BIN
+ test -v SRC
+ test -v TRG
+ model=/data/models/spoken-signed/spoken_to_signed/student-finetuned/final.model.npz.best-chrf.npz
+ vocab=/data/models/spoken-signed/spoken_to_signed/vocab/vocab.spm
+ shortlist=/data/data/spoken-signed/spoken_to_signed/alignment/lex.s2t.pruned.gz
+ devtest_src=/data/data/spoken-signed/spoken_to_signed/original/devset.spoken.gz
+ output_dir=/data/models/spoken-signed/spoken_to_signed/speed
++ dirname pipeline/quantize/quantize.sh
+ cd pipeline/quantize
+ res_model=/data/models/spoken-signed/spoken_to_signed/speed/model.intgemm.alphas.bin
+ mkdir -p /data/models/spoken-signed/spoken_to_signed/speed
+ cp /data/models/spoken-signed/spoken_to_signed/vocab/vocab.spm /data/models/spoken-signed/spoken_to_signed/speed
+ echo '### Decoding a sample test set in order to get typical quantization values'
### Decoding a sample test set in order to get typical quantization values
+ test -s /data/models/spoken-signed/spoken_to_signed/speed/quantmults
+ /firefox-translations-training/3rd_party/browsermt-marian-dev/build/marian-decoder -m /data/models/spoken-signed/spoken_to_signed/student-finetuned/final.model.npz.best-chrf.npz -v /data/models/spoken-signed/spoken_to_signed/vocab/vocab.spm /data/models/spoken-signed/spoken_to_signed/vocab/vocab.spm -c decoder.yml -i /data/data/spoken-signed/spoken_to_signed/original/devset.spoken.gz -o /data/models/spoken-signed/spoken_to_signed/speed/output.signed --shortlist /data/data/spoken-signed/spoken_to_signed/alignment/lex.s2t.pruned.gz false --quiet --quiet-translation --log /data/models/spoken-signed/spoken_to_signed/speed/cpu.output.log --dump-quantmult
pipeline/quantize/quantize.sh: line 41: 33155 Aborted                 (core dumped) "${BMT_MARIAN}"/marian-decoder -m "${model}" -v "${vocab}" "${vocab}" -c "decoder.yml" -i "${devtest_src}" -o "${output_dir}/output.${TRG}" --shortlist "${shortlist}" false --quiet --quiet-translation --log "${output_dir}/cpu.output.log" --dump-quantmult 2> "${output_dir}/quantmults"
```

Running just the last command to get the full output of it (`marian-decoder`...) without the (`--quiet`) flag, ends with:

```log
[2023-11-08 12:41:15] Error: Rows of matrix: param must be multiple of 8.
[2023-11-08 12:41:15] Error: Aborted from marian::cpu::integer::PrepareBNodeOp<vtype>::PrepareBNodeOp(marian::Expr, marian::Expr, float, bool) [with marian::Type vtype = (marian::Type)257u; marian::Expr = IntrusivePtr<marian::Chainable<IntrusivePtr<marian::TensorBase> > >] in /firefox-translations-training/3rd_party/browsermt-marian-dev/src/tensors/cpu/intgemm_interface.h:92
```

## My suspicion:
I am using a vocab size of 1668 since I am using a character level vocabulary.
All of the steps until now worked fine, except for this quantization step.
Is there a way to pad the matrix size to a multiple of 8?

(If I try to specify a vocab size of 1672 for example, `spm_train` fails since I have to make it less or equal to 1668)

This line exists in the marian-dev fork:
https://github.com/browsermt/marian-dev/blob/master/src/tensors/cpu/intgemm_interface.h#L90
But not in marian-dev actually.

## Alternative solutions

Add dummy entries to your vocabulary file until it reaches a size that is a multiple of 8. These entries can be random or placeholder tokens that are unlikely to appear in your training data.

This will require me to train everything again, and will require an error in the `spm-train` script to prevent vocab sizes that are not multiples of 8

**Comment by eu9ene** [comment]
I'm happy you were able to run it up to quantization :) I can't comment on any details of your issue since I'm not very familiar with Marian's code, but we run CI with vocab size 1000 and it works https://github.com/mozilla/firefox-translations-training/blob/main/configs/config.ci.yml

**Comment by AmitMY** [comment]
I think my guess still remains - 1000 is divisible by 8 (125), 1668 is not (208.5) so it might be the vocab size...
Issue for `marian-dev` https://github.com/browsermt/marian-dev/issues/107

**Comment by AmitMY** [comment]
(I am running another training job with a padded vocabulary of size 1672 to verify that the vocabulary was the issue. I'll know in 3-4 days)

**Comment by AmitMY** [comment]
works with multiple of 8. error to user is a good enough solution
