### ISSUE TITLE
Install pigz on generic worker

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#251]
We're going to work with huge datasets for high-resource languages (maybe 500m+ sentences) and some tools like OpusTrainer support only gzip. The current workaround is to decompress the corpus and to use a worker with 1tb of disk. 

Our main tool to work with gzip compression format is `pigz` which supports parallelization and can utilize all the CPUs on a machine.

It's hard to say which solution is more cost-efficient, but having the option to decompress on the fly would still be useful.

Also, ideally, we should use the docker images available in the repo to easier modify the environment if needed.

**Comment by bhearsum** [comment]
I recommend we add this as a toolchain instead. This would likely be faster than building a new image, and will also allow us to easily upgrade in the future. It's pretty straightforward to do this. We need:
* A [new fetch entry](https://github.com/mozilla/firefox-translations-training/blob/ff35476e16985c3cc9e21e50356a4c90efb623d0/taskcluster/ci/fetch/toolchains.yml#L37-L42)
* A [new toolchains entry](https://github.com/mozilla/firefox-translations-training/blob/main/taskcluster/ci/toolchain/kind.yml#L92-L101)
* A [simple wrapper script to build and package](https://github.com/mozilla/firefox-translations-training/blob/main/taskcluster/scripts/toolchain/build-extract-lex.sh)

**Comment by eu9ene** [comment]
closing per #430
