### ISSUE TITLE
Update Marian to 1.12

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#256]
https://github.com/marian-nmt/marian-dev/releases

We're on 1.10.25 based on training logs.

**Comment by bhearsum** [comment]
Assuming nothing about the compilation process changes, https://github.com/mozilla/firefox-translations-training/blob/ff35476e16985c3cc9e21e50356a4c90efb623d0/taskcluster/ci/fetch/toolchains.yml#L10 should be all that's needed to pick up the new version. (Of course...there might be necessary changes if the new version causes errors in the pipeline.)
