### ISSUE TITLE
Support augmentation with inline noise 

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#261]
Currently, it doesn't work because of the issue with tokenization, we might need to add another alignment step with tokenization based on spaces or update OpusTrainer to support Sentencepiece tokenized alignments.

see https://github.com/hplt-project/OpusTrainer/issues/38

**Comment by marco-c** [comment]
We probably don't need this one, it is used to provide "vocabulary hints".

**Comment by eu9ene** [comment]
Yes, it seems we can use the inline noise modifier instead since it's what we need - to leave words that models doesn't know untranslated.
