### ISSUE TITLE
`make tensorboard` fails

### ISSUE THREAD

**Issue by AmitMY** [mozilla/firefox-translations-training#263]
https://github.com/mozilla/firefox-translations-training/blob/main/Makefile#L177

I imagine tgere needs to be a previous step - 
```bash
mamba create -c conda-forge -n tensorboard --yes
$(CONDA_ACTIVATE) tensorboard
```

Otherwise, I get:
```
/bin/bash: line 1: poetry: command not found
/bin/bash: line 2: marian-tensorboard: command not found
```

**Comment by gregtatum** [comment]
It looks like `poetry` install needs to be part of the Makefile. A workaround would be to install it manually on the machine.

Here is a random example how to do it: https://blog.mathieu-leplatre.info/tips-for-your-makefile-with-python.html

**Comment by eu9ene** [comment]
Currently, poetry installation is a prerequisite to work with Makefile. We can either leave it as is and make it more explicit in the development readme or add installation to every rule which we btw do anyway in CI steps. I'd prefer to have a separate makefile rule to install poetry and then assume that it's installed.

**Comment by AmitMY** [comment]
I think a separate step is great, it will make it consistent between what I will run and what you run in CI (`make poetry` or something)

I still think that the conda environment might need to be activated, since otherwise how would it know what is `marian-tensorboard`?

**Comment by eu9ene** [comment]
We're switching to W&B, so Tensorboard is not needed anymore.
