### ISSUE TITLE
Support interactive tasks

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#269]

**Comment by bhearsum** [comment]
I tried doing this and ended up with [this task](https://firefox-ci-tc.services.mozilla.com/tasks/NPkPGAhRSniMWW6qDE9fzA) in an `exception` state with this error:
```
[taskcluster:error] &errors.errorString{s:"WORKER EXCEPTION due to response code 400 from Queue when uploading artifact &artifacts.RedirectArtifact{BaseArtifact:(*artifacts.BaseArtifact)(0xc0000cc5d0), URL:\"https://firefoxci-websocktunnel.services.mozilla.com/us-central1.1482915570372708027.60099/log/UOCNgLyGTFmVOqOu_bGYTw\", ContentType:\"text/plain; charset=utf-8\"} with CreateArtifact payload {\"contentType\":\"text/plain; charset=utf-8\",\"expires\":\"2023-12-20T20:07:34.165Z\",\"storageType\":\"reference\",\"url\":\"https://firefoxci-websocktunnel.services.mozilla.com/us-central1.1482915570372708027.60099/log/UOCNgLyGTFmVOqOu_bGYTw\"} - HTTP response body: {\n  \"code\": \"InputError\",\n  \"message\": \"Artifact expires (2023-12-20T20:07:34.165Z) after the task expiration 2023-11-27T19:49:29.312Z (task.expires < expires) - this is not allowed, artifacts may not expire after the task they belong to expires\\n\\n---\\n\\n* method:     createArtifact\\n* errorCode:  InputError\\n* statusCode: 400\\n* time:       2023-11-20T19:52:34.345Z\",\n  \"requestInfo\": {\n    \"method\": \"createArtifact\",\n    \"params\": {\n      \"0\": \"public/logs/live.log\",\n      \"taskId\": \"NPkPGAhRSniMWW6qDE9fzA\",\n      \"runId\": \"0\",\n      \"name\": \"public/logs/live.log\"\n    },\n    \"payload\": {\n      \"contentType\": \"text/plain; charset=utf-8\",\n      \"expires\": \"2023-12-20T20:07:34.165Z\",\n      \"storageType\": \"reference\",\n      \"url\": \"https://firefoxci-websocktunnel.services.mozilla.com/us-central1.1482915570372708027.60099/log/UOCNgLyGTFmVOqOu_bGYTw\"\n    },\n    \"time\": \"2023-11-20T19:52:34.345Z\"\n  }\n}"}
[taskcluster:error] WORKER EXCEPTION due to response code 400 from Queue when uploading artifact &artifacts.RedirectArtifact{BaseArtifact:(*artifacts.BaseArtifact)(0xc0000cc5d0), URL:"https://firefoxci-websocktunnel.services.mozilla.com/us-central1.1482915570372708027.60099/log/UOCNgLyGTFmVOqOu_bGYTw", ContentType:"text/plain; charset=utf-8"} with CreateArtifact payload {"contentType":"text/plain; charset=utf-8","expires":"2023-12-20T20:07:34.165Z","storageType":"reference","url":"https://firefoxci-websocktunnel.services.mozilla.com/us-central1.1482915570372708027.60099/log/UOCNgLyGTFmVOqOu_bGYTw"} - HTTP response body: {
[taskcluster:error]   "code": "InputError",
[taskcluster:error]   "message": "Artifact expires (2023-12-20T20:07:34.165Z) after the task expiration 2023-11-27T19:49:29.312Z (task.expires < expires) - this is not allowed, artifacts may not expire after the task they belong to expires\n\n---\n\n* method:     createArtifact\n* errorCode:  InputError\n* statusCode: 400\n* time:       2023-11-20T19:52:34.345Z",
[taskcluster:error]   "requestInfo": {
[taskcluster:error]     "method": "createArtifact",
[taskcluster:error]     "params": {
[taskcluster:error]       "0": "public/logs/live.log",
[taskcluster:error]       "taskId": "NPkPGAhRSniMWW6qDE9fzA",
[taskcluster:error]       "runId": "0",
[taskcluster:error]       "name": "public/logs/live.log"
[taskcluster:error]     },
[taskcluster:error]     "payload": {
[taskcluster:error]       "contentType": "text/plain; charset=utf-8",
[taskcluster:error]       "expires": "2023-12-20T20:07:34.165Z",
[taskcluster:error]       "storageType": "reference",
[taskcluster:error]       "url": "https://firefoxci-websocktunnel.services.mozilla.com/us-central1.1482915570372708027.60099/log/UOCNgLyGTFmVOqOu_bGYTw"
[taskcluster:error]     },
[taskcluster:error]     "time": "2023-11-20T19:52:34.345Z"
[taskcluster:error]   }
```

**Comment by bhearsum** [comment]
Good news...it turns out that interactive tasks work...it's just the button that creates them easily doesn't when maxRunTime is so big. This is filed as https://github.com/taskcluster/taskcluster/issues/6696

In the meantime, you can get an interactive task by doing this instead:
* Go to the task you want an interactive version of, eg: https://firefox-ci-tc.services.mozilla.com/tasks/DZvVQ-VUTPSyPBBS13Bwfg
* Click the "Edit" button in the three dots menu
* Click "Edit" on the modal that pops up
* Click the "Interactive" toggle in the top left
* Reduce the `maxRunTime` to something much smaller. (I've been using a 7200 in my tests, but I _think_ anything up to 1 day will work.)
* Click "Create Task"

After a few minutes you should be able to get a shell (a link will show up in the tab when it's ready).

**Comment by eu9ene** [comment]
@bhearsum it didn't work for me:

<img width="2526" alt="Screenshot 2023-12-13 at 4 26 46 PM" src="https://github.com/mozilla/firefox-translations-training/assets/2486505/261ec49f-2db9-4b4c-b70d-27f79cacd2c3">

**Comment by bhearsum** [comment]
Ah, looks like an oversight from https://bugzilla.mozilla.org/show_bug.cgi?id=1867530. I'm handling it in https://bugzilla.mozilla.org/show_bug.cgi?id=1869936.

**Comment by bhearsum** [comment]
This should be working now - you'll need to logout and log back into Taskcluster to pick up the new scope.

**Comment by eu9ene** [comment]
@bhearsum I was able to save the task and get a shell link but when I click on it it shows this:

<img width="2523" alt="Screenshot 2023-12-14 at 10 28 11 AM" src="https://github.com/mozilla/firefox-translations-training/assets/2486505/5a92d8ca-bd15-4546-a687-91d914408754">

It seems there's an issue with permissions. Is it supposed to open the shell right in the browser? Or should I ssh somewhere?

**Comment by bhearsum** [comment]
Yep, we missed another scope (permission). I've just added that in https://bugzilla.mozilla.org/show_bug.cgi?id=1870131 - give the logout/login/interactive task another try :crossed_fingers:.

**Comment by bhearsum** [comment]
https://github.com/mozilla/firefox-translations-training/pull/307 for the docs.

**Comment by eu9ene** [comment]
@bhearsum I tried to edit this task https://firefox-ci-tc.services.mozilla.com/tasks/JsgghZIiRn6kpjRTZja75A and there's this error:
<img width="926" alt="Screenshot 2023-12-21 at 9 45 25 AM" src="https://github.com/mozilla/firefox-translations-training/assets/2486505/b9dadc1e-4c1c-4486-ae1c-05fc4b21e8fa">

**Comment by bhearsum** [comment]
This should be fixed now - give it another try.

**Comment by eu9ene** [comment]
Similar to the previous issues I can press the "shell" button now but it shows another error:
```
Client ID mozilla-auth0/ad|Mozilla-LDAP|epavlov does not have sufficient scopes and is missing the following scopes:\n\n```\nqueue:get-artifact:private/generic-worker/shell.html\n```\n\nThis request requires the client to satisfy the following scope expression:\n\n```\n{\n  "AllOf": [\n    "queue:get-artifact:private/generic-worker/shell.html"\n  ]\n}\n```\n\n---\n\n* method:     getLatestArtifact\n* errorCode:  InsufficientScopes\n* statusCode: 403\n* time:       2023-12-21T18:28:27.540Z
```

**Comment by eu9ene** [comment]
ok, it's working now, I'm closing the issue then
