### ISSUE TITLE
Provide basic toolset in interactive tasks

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#330]
We should be able to edit and run code inside the interactive tasks.

Some common debugging tools we need preinstalled (some of them are installed in the generic-worker but not installed in the docker worker)
- nvidia-smi for gpu
- tmux
- htop
- vim
- nano
- zstd

**Comment by gregtatum** [comment]
* curl
* git

**Comment by bhearsum** [comment]
#372 addresses this for the non-GPU tasks by installing them into the base Docker image used when building all of the concrete images used for various tasks. GPU workers will be dealt with in a pull request to https://github.com/mozilla-platform-ops/monopacker, and a patch like https://phabricator.services.mozilla.com/D198031 to upgrade the underlying worker images.

**Comment by bhearsum** [comment]
New image with these tools is rolling out in https://bugzilla.mozilla.org/show_bug.cgi?id=1876326.

**Comment by bhearsum** [comment]
The new GPU worker image has been rolled out - I believe we're all done with this issue.
