### ISSUE TITLE
Publish training charts from Taskcluster

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#333]
This includes publishing:
- live training logs to W&B dashboards

I assume we'll have separate publishing scripts for other things.

Let's use [Taskgraph transforms](https://taskcluster-taskgraph.readthedocs.io/en/latest/concepts/transforms.html) not to pollute Taskcluster kinds with even more logic.

**Comment by La0** [comment]
We can start working on this now.

I identified these next steps to discuss together:

1. build a dedicated command in the tracking package to support specific tasks (training & evaluation) and use a Taskcluster secret to get the Weight & Biases token
2. Setup the publication code through a Taskcluster transform
3. Patch training shell scripts to capture output and publish from logs
   - when an env variable is set
   - scripts to patch 
      - `pipeline/train/train.sh`
      - `pipeline/train/spm-vocab.sh`
4. Identify other tasks to track & publish

**Comment by La0** [comment]
After discussion with Evgeny, we can start to build the dedicated script to interact with Taskcluster secret & logs.

**Comment by eu9ene** [comment]
One small correction: `pipeline/train/spm-vocab.sh` trains a vocab and we don't want to track this in W&B. So only `train.sh` should be patched.

**Comment by La0** [comment]
@evabardou will work on [Taskcluster secret support](https://github.com/mozilla/firefox-translations-training/issues/481).

We can start experimenting log parsing from CI using `--in-stream` option too
