### ISSUE TITLE
Add missing steps for experiment tracking

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#334]
I noticed that we currently publish only the steps that have training procedure for. We should also publish the results from evaluation steps to separate W&B runs for easy comparison between all the models:
- teacher-ensemble (`evaluate-teacher-ensemble-<dataset>` for Taskcluster: [example](https://firefox-ci-tc.services.mozilla.com/tasks/groups/EW7qV3U5SBSjegnTxGZHkw#evaluate-teacher-ensemble))
- quantized (`speed` directory for old experiments, `evaluate-quantized-<dataset>` results for Taskcluster: [example](https://firefox-ci-tc.services.mozilla.com/tasks/groups/EW7qV3U5SBSjegnTxGZHkw#evaluate-quantized))

Also keep in mind that sometimes we'll use pre-trained models (see #226) and will not run training at all for some steps (likely backward and teacher) but only run evaluation.

**Comment by vrigal** [comment]
From what I undestand correctly, we look for those lines the deduce BLEU/chrF values:
```
[task 2023-11-19T22:17:20.883Z] + tee /home/ubuntu/tasks/task_170043216179759/artifacts/wmt19.metrics
[task 2023-11-19T22:17:51.898Z] 26.3
[task 2023-11-19T22:17:51.898Z] 54.4
```
This example is from [evaluate-student-sacrebleu-wmt19-lt-en](https://firefox-ci-tc.services.mozilla.com/tasks/Gh40h_m4T0yxZB1zucgXdA/runs/0/logs/public/logs/live.log).

The parser is only able to read the `metrics` file actually, but I can probably patch `tracking.translations_parser.data.Metric.from_file` method to support a TC context (with that explicit rule looking for a single line matching `tee <path>/<metric_name>.metrics` followed by two float values).

**Comment by vrigal** [comment]
I'm working on this (together with #336) for the existing experiments (no TC context yet), but have difficulties identifying the right data.
Actually I'm parsing files at `logs/<project>/<group>/eval/eval_*.log` (e.g. `logs/en-nl/prod/eval/eval_teacher-ensemble_mtdata_Neulab-tedtalks_test-1-eng-nld.log`), and I'm not sure how to extract the different information from the file name. (i.e in this example model (run): `teacher-ensemble` and dataset: `mtdata_Neulab-tedtalks_test-1`).

**Comment by eu9ene** [comment]
> From what I undestand, we look for those lines to deduce BLEU/chrF values:
> 
> ```
> [task 2023-11-19T22:17:20.883Z] + tee /home/ubuntu/tasks/task_170043216179759/artifacts/wmt19.metrics
> [task 2023-11-19T22:17:51.898Z] 26.3
> [task 2023-11-19T22:17:51.898Z] 54.4
> ```
> 
> This example is from [evaluate-student-sacrebleu-wmt19-lt-en](https://firefox-ci-tc.services.mozilla.com/tasks/Gh40h_m4T0yxZB1zucgXdA/runs/0/logs/public/logs/live.log).
> 
> The parser is only able to read the `metrics` file actually, but I can probably patch `tracking.translations_parser.data.Metric.from_file` method to support a TC context (with that explicit rule looking for a single line matching `tee <path>/<metric_name>.metrics` followed by two float values).
> 
> edit: `speed` folder metrics are already published for old experiments (on the `group_logs` fake run).

The `.metrics` files are available as artifacts for the TC run and I download them [here](https://github.com/mozilla/firefox-translations-training/blob/673916fbf5eadfaae5ee1759b73c51d1c7f676cb/utils/taskcluster_downloader.py#L100) in my temporary util.

>I'm working on this (together with https://github.com/mozilla/firefox-translations-training/issues/336) for the existing experiments (no TC context yet), but have difficulties identifying the right data.
Actually I'm parsing files at logs/<project>/<group>/eval/eval_*.log (e.g. logs/en-nl/prod/eval/eval_teacher-ensemble_mtdata_Neulab-tedtalks_test-1-eng-nld.log), and I'm not sure how to extract the different information from the file name. (i.e in this example model (run): teacher-ensemble and dataset: mtdata_Neulab-tedtalks_test-1).

Yes this is correct. The format is `eval_<model>_<dataset>`. The dataset in fact includes `<importer>_<dataset name>`. And for new runs on TC `<importer>_<optional augmentation>_<dataset name>`. See more details in the [datsets docs](https://mozilla.github.io/firefox-translations-training/data.html) and [opus trainer docs](https://mozilla.github.io/firefox-translations-training/opus-trainer.html#evaluation). The experiments I uploaded to GCP are from different times so there might be some inconsistencies in structure. I think teacher steps might be called differently, so we should account for this in the parsing.
