### ISSUE TITLE
Publish all evaluation results on experiment dashboard

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#336]
There should be a way to look at all the evaluation and compare them across models and experiments. Let's think what would be the most convenient way to do that. We already publish some of them inside each step and have a dashboard to compare (it's not clear what values are those though). Let's see what's missing.

Having [such table](https://docs.google.com/spreadsheets/d/1wKdbPN8XzAmAaVJMwYENWb1JvOQe3s3ScRy8Kgz1LhQ/edit#gid=66711953) for the whole experiment would be very convenient for analysis, so we should either add an extra table to the `group_logs` step or to the overview for the group.

<img width="699" alt="Screenshot 2024-01-03 at 4 36 48 PM" src="https://github.com/mozilla/firefox-translations-training/assets/2486505/724c4c2a-0adb-43fd-b4a2-20f0565e76b3">

Related to #334

**Comment by vrigal** [comment]
`.metrics` files from the experiments structure are actually found at `models/en-sv/<group-name>/evaluation/student/*.metrics`. Should I keep this behavior and publish those values on each run ?

From the data you show I think I should rather parse values from files at `logs/en-nl/prod/eval/eval_*` (as specified in #334, without TC context), to publish them as a table on `group_logs` fake run ?

**Comment by eu9ene** [comment]
As we discussed we need both. We need the evaluation data published as steps and you're already doing it for the training runs + we should add the steps that don't have training (see #334). This will allow us to use W&B comparison across the runs. It would also be great to publish everything to the experiment dashboard on group logs, similar to the table.
