### ISSUE TITLE
Permissions issues in interactive tasks

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#354]
We also investigate issues with permissions while running scripts inside the interactive tasks. For example, I had "permission denied" after launching a pipeline script that creates a directory ("./artefacts"). I think the permissions should include those that we have for the jobs + maybe some extra ones if a user wants to install some tools (think near root).

**Comment by bhearsum** [comment]
@eu9ene - can we try to do this over Zoom one day so I can see exactly what you're hitting? I tried it myself just now and I was able to write to the artifacts directory, the fetches directory, and even use `sudo` to install things. (Perhaps the most recent image update fixed things...or perhaps I'm not doing what you're doing.)

**Comment by eu9ene** [comment]
I can install packages with sudo now. Ok, if it works for you we can close this now and reopen if we encounter issues again.
