### ISSUE TITLE
Disable spot instances for training

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#356]
We should use regular GCP instances for the long training jobs since it increases wait time and uncertainty for a person who run an experiment:
train-backward
train-teacher
train-student

We can enable spot instances again when we setup training continuation on restart: #270

**Comment by gabrielBusta** [comment]
[Bug 1875371](https://bugzilla.mozilla.org/show_bug.cgi?id=1875371) - [Add standard VM worker pools for machine learning tasks r?bhearsum,#releng-reviewers](https://phabricator.services.mozilla.com/D199031)
