### ISSUE TITLE
Use full Bicleaner-AI models

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#360]
They significantly outperform the light ones based on the [paper](https://aclanthology.org/2022.lrec-1.87.pdf). Inference speed will be slower but it's fine since now we have an ability to easily scale both vertically and horizontally. We used those models for the Snakemake pipeline on Berlin cluster but we're using the light ones on Taskcluster for some reason.

**Comment by TommiNieminen** [comment]
As part of the GreenNLP project we've been running full bicleaner-AI models for the Tatoeba-Challenge corpus (containing most of OPUS data) for all the language pairs available and saving the score files for reuse. We intend to make the score files publicly available soon.

**Comment by marco-c** [comment]
@eu9ene maybe with your patch you could store the score files as artifacts, so they are publicly available too.

**Comment by eu9ene** [comment]
yes, we store them as artifacts
