### ISSUE TITLE
Investigate automatic generation of cleaning rules using OpusFilter

### ISSUE THREAD

**Issue by marco-c** [mozilla/firefox-translations-training#370]
This would allow to more quickly define cleaning rules.

https://helsinki-nlp.github.io/OpusFilter/automatic_configuration.html

**Comment by eu9ene** [comment]
I ran a lot of experiments trying to utilize automatic threshold generation with OpusFilter and basically couldn't beat the defaults with it. I tried various combinations of regular cleaning rules and also combined them with Bicleaner-AI and LASER.

More details in the PR: https://github.com/mozilla/firefox-translations-training/pull/517

My conclusion is even if it can work it would require a significant effort to polish the method and it's not clear how much benefit it would bring.
