### ISSUE TITLE
Bump bicleaner-ai dependency

### ISSUE THREAD

**Issue by marco-c** [mozilla/firefox-translations-training#378]
We are still using 2.0 (https://github.com/mozilla/firefox-translations-training/blob/71013bcea0e4647d04d508daf45fe2a96c27ef0d/pipeline/bicleaner/requirements/bicleaner-ai.in), but the latest version is 2.3.2.

2.2.0 adds support for tokenizing by characters (for Chinese).

**Comment by marco-c** [comment]
The full models are now stored on HuggingFace though, so not available anymore through https://github.com/bitextor/bicleaner-ai-data/releases.

**Comment by eu9ene** [comment]
We should update to 3.0, so closing in favour of #528. Also, we're already using the models from HF.
