### ISSUE TITLE
Cannot cancel an interactive task

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#389]
https://firefox-ci-tc.services.mozilla.com/tasks/RP0DAQEJQ4afVkcV39QO5g

Missing scopes:

{
  "AnyOf": [
    "queue:cancel-task:taskcluster-ui/RP0DAQEJQ4afVkcV39QO5g/RP0DAQEJQ4afVkcV39QO5g",
    "queue:cancel-task-in-project:none",
    {
      "AllOf": [
        "queue:cancel-task",
        "assume:scheduler-id:taskcluster-ui/RP0DAQEJQ4afVkcV39QO5g"
      ]
    }
  ]
}

@bhearsum

**Comment by bhearsum** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1876299 for this; should be fixed sometime today
