### ISSUE TITLE
Allow expert user to configure mini-batch size when decoding

### ISSUE THREAD

**Issue by XapaJIaMnu** [mozilla/firefox-translations-training#40]
The default mini batch size setting:
https://github.com/eu9ene/bergamot-training/blob/quality/pipeline/translate/decoder.yml
```
normalize: 1.0
word-penalty: 0
mini-batch: 16
mini-batch-words: 2000
maxi-batch: 1000
maxi-batch-sort: src
max-length: 200
max-length-crop: true
beam-size: 8
quiet-translation: True
```
Is not adequate for all models involved. The s2s model used for backtranslation could easily have 512 mini-batch size on a 3090ti and much larger maxi-batch and mini-batch words. That would yield up to **4X** improvement in translation speed, as shown on table 4: http://statmt.org/wmt21/pdf/2021.wmt-1.74.pdf

It is good to have safe default values for non-expert users, but for getting the most of our limited hardware budget, those need to be easily adjustable configuration options. Also the settings for the teacher models and for the backtranslation models would have to be different.

**Comment by eu9ene** [comment]
Yes, we should split the decoding config for teachers and backward models. I encountered this myself recently and had to set safe `mini-batch-words: 500` to translate with ensemble of 4 teachers on 12GB GPU. 

Another question is configuration. There are too many different configs that a user needs to adjust based on data and hardware. I'm still figuring out how to organize them better. Ideally we need to tune hardware dependent settings automatically, depending on amount of GPU memory etc.

**Comment by eu9ene** [comment]
@XapaJIaMnu do you have any recommendations on how to tune these parameters to maximize GPU utilization and decoding speed?

**Comment by XapaJIaMnu** [comment]
We can probably do some rule based system to generate some safe/optimal settings with experimentation.

Eg, the mini-batch words for teacher translation should be a function of the number of teachers and the workspace provided.
Settings for backtranslation model should be similarly determined. I am not sure what hard and fast rules are but we can set some time aside to binary search some models and come up with some rough estimates (estimates will be rough because different languages have different source-to-target tokens ratio and that effects the memory usage.

Then what should happen is that a script should be run by the user to generate those optimised defaults  and place them in a file so that a non-expert user can use them out of the box and expert user can tune them.
