### ISSUE TITLE
Incompatible python version

### ISSUE THREAD

**Issue by AmitMY** [mozilla/firefox-translations-training#412]
For bicleaner, you use https://github.com/mozilla/firefox-translations-training/blob/main/pipeline/bicleaner/download_pack.py#L93
```py
def main(args: Optional[list[str]] = None) -> None:
```

which is not allowed in this environment, defined [here](https://github.com/mozilla/firefox-translations-training/blob/main/envs/bicleaner.yml) to use python 3.7

> Traceback (most recent call last):
  File "pipeline/bicleaner/download_pack.py", line 93, in <module>
    def main(args: Optional[list[str]] = None) -> None:
TypeError: 'type' object is not subscriptable

**Comment by marco-c** [comment]
Python 3.7 is end of life, we should bump at least to 3.8.

**Comment by eu9ene** [comment]
We don't have any issues with our current workflows. The supported Python versions are specified in poetry config and Docker images:

https://github.com/mozilla/firefox-translations-training/blob/04e9e9cdc369cc8efdf080d57eef805a61d2c35e/pyproject.toml#L9
