### ISSUE TITLE
Update mtdata version

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#43]
It allows using paracrawl v9

**Comment by eu9ene** [comment]
mtdata has introduced a new naming convention for datasets that includes `<src>-<trg>` languages. Updating will require handling our per-dataset fixes differently because right now the scripts are named as datasets without language dependency, for example, `pipeline/clean/fixes/mtdata_JW300.sh`

**Comment by kpu** [comment]
Given that JW300 was taken down from OPUS, I suppose `pipeline/clean/fixes/mtdata_JW300.sh` isn't an issue :crying_cat_face:.    But the other ones are.
