### ISSUE TITLE
Inconsistent dataset naming publishing Taskcluster group

### ISSUE THREAD

**Issue by vrigal** [mozilla/firefox-translations-training#449]
Follow-up of #406.
 
Label used from taskcluster is inconsistent among evaluations for runs and evaluations that does not have a run (thus displaying data in different graph):
* evaluate-student-flores-aug-typos_devtest-lt-en becomes "Flores-aug-typos_devtest-lt-en"
* evaluate-teacher-ensemble-flores-flores_aug-typos_devtest-lt-en becomes "Flores-flores_aug-typos_devtest-lt-en"

This can be fixed either by retrieving dataset name from the task, or handling the duplicate (e.g. `flores-flores…`).

**Comment by eu9ene** [comment]
Check out [this](https://github.com/mozilla/firefox-translations-training/blob/190358a9231c5b4e057bf465fcbcef783ddbcc34/utils/taskcluster_downloader.py#L23) regex, it might handle some problems with inconsistency.

**Comment by vrigal** [comment]
This regex has been used already to support those cases (from https://github.com/mozilla/firefox-translations-training/pull/406#issuecomment-1946702488) :
https://github.com/mozilla/firefox-translations-training/blob/190358a9231c5b4e057bf465fcbcef783ddbcc34/utils/taskcluster_downloader.py#L23-L39

**Comment by eu9ene** [comment]
Where? I don't see it in the tracking code, only in the utils. If it's being used it might miss some cases then so feel free to improve it.

**Comment by eu9ene** [comment]
Here is an example names from configs with the format we should use: 

`<importer>_<augmentation?>_<dataset>`

```
    - flores_devtest
    - flores_aug-title_devtest
    - flores_aug-upper_devtest
    - flores_aug-typos_devtest
    - flores_aug-noise_devtest
    - flores_aug-inline-noise_devtest
    - sacrebleu_wmt19
    - sacrebleu_aug-title_wmt19
    - sacrebleu_aug-upper_wmt19
    - sacrebleu_aug-typos_wmt19
    - sacrebleu_aug-noise_wmt19
    - sacrebleu_aug-inline-noise_wmt19
    - mtdata_Neulab-tedtalks_test-1-eng-lit
```

For the last one `mtdata` is importer and `Neulab-tedtalks_test-1-eng-lit` is a dataset name.

See data import [docs](https://mozilla.github.io/firefox-translations-training/data.html)  and augmentation [docs](https://mozilla.github.io/firefox-translations-training/opus-trainer.html#data-augmentation).
