### ISSUE TITLE
Teacher ensemble step is missing in Taskcluster publication

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#452]
When we publish experiment to W&B from Taskcluster the structure should be consistent with the experiments from GCP. `teacher-ensemble` step that should include only evaluation metrics is completely missing now.

Here is an example task that performs evaluation on an ensemble of teachers: https://firefox-ci-tc.services.mozilla.com/tasks/LI2VaGuITkOAFP-rWsZebg

**Comment by vrigal** [comment]
This is caused because `evaluate-teacher-ensemble` depends on `train-teacher`. We could either make an exception for those, or look for metrics without a run based on the tag value.
