### ISSUE TITLE
Train action is stuck when `start-stage` is being used

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#487]
I’m trying to run training with `start-stage` and my actions hang and then get killed on timeout: 

https://firefox-ci-tc.services.mozilla.com/tasks/f1vP7g6IRIuFswKEZdd05g 
https://firefox-ci-tc.services.mozilla.com/tasks/VyRu3YyTSxGtJxZ3RFaeIA/runs/0 

@bhearsum suggested that it's probably taking a tremendous amount of time to walk through all of the upstream tasks. We can try bumping [the timeout](https://github.com/mozilla/firefox-translations-training/blob/main/.taskcluster.yml#L230) and adding some [logging on either side of get_ancestors](https://github.com/mozilla/firefox-translations-training/blob/main/taskcluster/translations_taskgraph/actions/train.py#L365) as a quick test of that.

**Comment by eu9ene** [comment]
I think regardless of the reason it should not take more than several minutes to run actions otherwise it's quite unusable When using `start-stage` we often want to inspect what tasks the action schedules right away.

**Comment by bhearsum** [comment]
> I think regardless of the reason it should not take more than several minutes to run actions otherwise it's quite unusable When using `start-stage` we often want to inspect what tasks the action schedules right away.

I agree that it shouldn't, but it's not as easy as it seems. As far as I know, there's no way to bulk retrieve task metadata from Taskcluster, so we have to fetch each task one by one, then recursively do the same for each task's dependencies. (There [a proposal to improve this](https://github.com/taskcluster/taskcluster-rfcs/pull/189), but nothing implemented yet.)

If this is indeed the problem we may be able to parallelize to speed this up a bit in the meantime. There may also be alternative ways to implement this, or fetch the necessary information - I'll see if I can come up with anything.-

I've pushed https://firefox-ci-tc.services.mozilla.com/tasks/Z7LHp6PRT1m2QhYvPyUrRQ with logging + longer timeout to try to verify the theory.

**Comment by bhearsum** [comment]
After some iteration, I managed to test with additional logging and a much longer timeout, and it still failed with the same inputs:
```
[task 2024-03-21T14:56:58.903Z] executing ['bash', '-cx', 'cd /builds/worker/checkouts/src && ln -s /builds/worker/artifacts artifacts && ~/.local/bin/taskgraph action-callback\n']
[task 2024-03-21T14:56:58.906Z] + cd /builds/worker/checkouts/src
[task 2024-03-21T14:56:58.906Z] + ln -s /builds/worker/artifacts artifacts
[task 2024-03-21T14:56:58.908Z] + /builds/worker/.local/bin/taskgraph action-callback
[task 2024-03-21T14:56:59.786Z] 2024-03-21 14:56:59,785 - INFO - Fetching ancestors for tasks: e4bBbBRbSZmTDtKsPJZMkQ
[taskcluster:error] Task timeout after 10800 seconds. Force killing container.
```

Clearly the current approach to finding ancestors is not going to be viable for `start-stage`. Whether it's https://github.com/taskcluster/taskcluster-rfcs/pull/189 or something else I'll try to figure out another option.

**Comment by bhearsum** [comment]
> After some iteration, I managed to test with additional logging and a much longer timeout, and it still failed with the same inputs:
> 
> ```
> [task 2024-03-21T14:56:58.903Z] executing ['bash', '-cx', 'cd /builds/worker/checkouts/src && ln -s /builds/worker/artifacts artifacts && ~/.local/bin/taskgraph action-callback\n']
> [task 2024-03-21T14:56:58.906Z] + cd /builds/worker/checkouts/src
> [task 2024-03-21T14:56:58.906Z] + ln -s /builds/worker/artifacts artifacts
> [task 2024-03-21T14:56:58.908Z] + /builds/worker/.local/bin/taskgraph action-callback
> [task 2024-03-21T14:56:59.786Z] 2024-03-21 14:56:59,785 - INFO - Fetching ancestors for tasks: e4bBbBRbSZmTDtKsPJZMkQ
> [taskcluster:error] Task timeout after 10800 seconds. Force killing container.
> ```
> 
> Clearly the current approach to finding ancestors is not going to be viable for `start-stage`. Whether it's [taskcluster/taskcluster-rfcs#189](https://github.com/taskcluster/taskcluster-rfcs/pull/189) or something else I'll try to figure out another option.

Correct: after additional debugging it looks like we're simply fetching the same task definitions many, many times because they're referenced in many tasks. After adding some caching I got the action to complete in under a minute: https://firefox-ci-tc.services.mozilla.com/tasks/WtAmjBBISGGc_T901cKMvw/runs/0

This will require an upstream taskgraph fix, but should be straightforward.
