### ISSUE TITLE
Simplify and restructure the makefile and utilities

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#495]
We increasingly use the Makefile as an entry point for our local CLI tools and it's getting more complex. We should find a better way to organize the tooling code, make it easier to understand arguments and run the CLI tools.

See also https://github.com/mozilla/firefox-translations-training/pull/492#discussion_r1536162389

A few possible alternatives we discussed with @gregtatum:
- Reimplement some of the scripts as standalone Python scripts (pros: easier to maintain, argument parsing, docs; cons: takes some time to rewrite, more code compared to bash, maybe an overkill for such supplementary code)
- extract bash to separate bash scripts (pros: makefile becomes smaller, easier to inspect arguments in the code, ability to run separately; cons: still no interactive help, no argument parsing)
- bash + something for argument parsing and help (pros: easier to use than just bash; cons: the bash code might become complicated)
- find an alternative to Makefile (here is one after a quick search: https://taskfile.dev/)

**Comment by gregtatum** [comment]
I quite like Taskfile, it seems to satisfy all of the constraints, and is ergonomic. It would be a fairly trivial task to migrate over to it. It supports dependencies like Makefiles do. It can list commands, and provide a short description. It can also forward arguments to the underlying commands creating a single entry point into the tools. It lets you write bash as part of the commands. It has lots of install options for the different OSes.

```
➤ task --list-all
task: Available tasks for this project:
* black:                  Format the python code with black.
* download-logs:          Download the logs for taskcluster.
* opuscleaner-ui:         Run the opuscleaner tool.
* poetry-install-*:       Install only the group need for the dependencies of a task.
```

Example of migrating 4 tasks:

```
version: '3'

tasks:
  poetry-install-*:
    desc: Install only the group need for the dependencies of a task.
    vars:
      GROUP: '{{index .MATCH 0}}'
    cmds:
      - poetry install --only {{.GROUP}} --no-root

  download-logs:
    desc: Download the logs for taskcluster.
    deps: [poetry-install-utils]
    cmds:
      - >-
          poetry run python -W ignore utils/taskcluster_downloader.py
          --mode=logs {{.CLI_ARGS}}

  opuscleaner-ui:
    desc: Run the opuscleaner tool.
    deps: [poetry-install-opuscleaner]
    cmds:
      - opuscleaner-server serve --host=0.0.0.0 --port=8000

  black:
    desc: Format the python code with black.
    deps: [poetry-install-black]
    cmds:
      - >-
          if poetry run black . --check --diff; then
            echo "The python code formatting is correct.";
          else
            echo "";
            echo "Python code formatting issues detected.";
            echo "Run 'make black-fix' to fix them.";
            echo "";
            exit 1;
          fi
```

![Example colorized output for running a task.](https://github.com/mozilla/firefox-translations-training/assets/1588648/e6a17628-aa41-493b-8ea9-4d5df44a1526)

**Comment by eu9ene** [comment]
It looks nice! It reminds me of Snakemake a little :) They have a similar concept of wildcards and caching. It can solve our problems with ergonomics for sure. We can also extract some of the bigger scripts to separate files if that helps.

**Comment by gregtatum** [comment]
I'm happy making this bug into implementing Taskfile if you are. I can take it.
