### ISSUE TITLE
Publish evals from Taskcluster

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#519]

**Comment by La0** [comment]
@eu9ene Could you link here all the Taskcluster kind files you want to track ?

**Comment by eu9ene** [comment]
Everything that starts from "evaluate":
https://github.com/mozilla/firefox-translations-training/blob/main/taskcluster/kinds/evaluate-quantized/kind.yml
https://github.com/mozilla/firefox-translations-training/blob/main/taskcluster/kinds/evaluate-teacher-ensemble/kind.yml
https://github.com/mozilla/firefox-translations-training/blob/main/taskcluster/kinds/evaluate/kind.yml

The goal is to integrate everything we had in the offline publisher.

Also, we should reuse the code from the offline publisher that maps the task label to the training steps to keep the naming consistent.
