### ISSUE TITLE
Publish experiment config from Taskcluster

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#521]

**Comment by vrigal** [comment]
@eu9ene to be sure, this concerns online publication and we want to publish experiment config (from task group) in a `group_log` run (as for old experiments) ?
I'm wondering what would be the best entrypoint to build this run, maybe it should be triggered when creating any run, if no `group_log` run already exists on this group ?

**Comment by eu9ene** [comment]
Yes, it is similar to the experiment configs that we publish in `group_log` for the old experiments. It lives in the train action.

Since we track only the training tasks now (+evals later), I think it would make sense to upload the config/create `group_log` only when the first training task is started. Otherwise, we would have a lot of groups with only `group_log` and no other runs because we often test cleaning and things fail before we reach training.

Maybe we can just call a Python script right before we start training in the `train.sh`. Or even inside the `parse_tc_logs` script to be sure we sync this with training.
