### ISSUE TITLE
Publish task logs from Taskcluster

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#522]
We are especially interested in publishing the full training live.log as a file to W&B artifacts or logs (wherever it will be more convenient to view it). 

This can be published when the run is finished. We can view the live log directly in Taskcluster. I assume we can publish the live log not only for training but also for evaluation steps since it will be a very similar mechanism (likely transform).

**Comment by La0** [comment]
If you want the full task log, the only way would be to introduce an extra task that runs after the training/evaluation tasks are done and publish their full log as seen by Taskcluster

**Comment by eu9ene** [comment]
I see, it makes sense. Ok, to make things easier let's publish only the output from OpusTrainer and Marian.
