### ISSUE TITLE
Bicleaner Ai multilingual model

### ISSUE THREAD

**Issue by ZJaume** [mozilla/firefox-translations-training#55]
I've seen that you integrate Bicleaner in your pipeline and you choose the tool based on available languages. FYI there's the [full en-xx](https://github.com/bitextor/bicleaner-ai-data/releases/download/v1.0/full-en-xx.tgz) model that is trained with the concatenation of all other languages and performs quite decent on unseen languages. I've been using it for Turkish, Albanian and Macedonian, and it seemed nice when eyeballing. Unfortunately I don't have a comparison between using and not using it.

**Comment by eu9ene** [comment]
Also use `--disable_hardrules` as it was suggested [here](https://github.com/mozilla/firefox-translations-training/issues/71#issuecomment-1040029744).
