### ISSUE TITLE
training runs don't log properly to stdout/stderr anymore

### ISSUE THREAD

**Issue by bhearsum** [mozilla/firefox-translations-training#552]
Ever since weights & biases tracking was enabled I've noticed that training runs don't log everything to stdout/stderr to the regular Taskcluster log. For example, [in this task](https://firefox-ci-tc.services.mozilla.com/tasks/LJkSU9LHTNuL9j2GYOHUZw/runs/0/logs/public/logs/live.log), the last output before the task was spot killed was:
```
[task 2024-05-01T18:55:47.282Z] [2024-05-01 18:55:47] [comm] Using global sharding
```

Yet there's much, much more output in [weights and biases](https://wandb.ai/moz-translations/en-ru/runs/86aqftri/logs?nw=nwuserepavlov).

It's not clear to me if stdout/stderr from the process simply aren't flushing as often, or if nothing is written to them at all after a certain point.

**Comment by La0** [comment]
I do not know why this specific task did not output anymore logs after that line: other tasks do publish on stdout.

Every parsed line should be printed back on stdout [there](https://github.com/mozilla/firefox-translations-training/blob/main/tracking/translations_parser/parser.py#L163)

**Comment by bhearsum** [comment]
> I do not know why this specific task did not output anymore logs after that line: other tasks do publish on stdout.
> 
> Every parsed line should be printed back on stdout [there](https://github.com/mozilla/firefox-translations-training/blob/main/tracking/translations_parser/parser.py#L163)

My suspicion is that stdout is not flushing. This is something we deal with in taskgraph as well: https://github.com/taskcluster/taskgraph/blob/71fe1d00a0f98b29ffd46f64a4a98713fe321173/src/taskgraph/run-task/run-task#L121
