### ISSUE TITLE
CI pollutes W&B

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#553]
See https://wandb.ai/moz-translations/ru-en, the runs appear to be fresh.

**Comment by bhearsum** [comment]
This may be a problem for certain branches as well. For example, I've been testing some things on branches and end up publishing to things like https://wandb.ai/moz-translations/en-ru/runs/xiv7n2y9?nw=nwuserepavlov.

Maybe we should have an allowlist of branches that we should publish from? Eg: `main` and maybe anything prefixed with `train/`?

**Comment by La0** [comment]
I'm looking into this:
- [This run](https://wandb.ai/moz-translations/ru-en/runs/z9hye5h5/overview?nw=nwuserbabadiemoz) was published earlier today
- Its Taskcluster group id is [GlH40tALR_anPycUXDqOGw](https://firefox-ci-tc.services.mozilla.com/tasks/groups/GlH40tALR_anPycUXDqOGw)
- The [training task](https://firefox-ci-tc.services.mozilla.com/tasks/U-cLxfzqSQ-FJuklSkEzCA/definition) is correctly set with `WANDB_AUTOMATION=False` and the code respects it: we can see [in the logs](https://firefox-ci-tc.services.mozilla.com/tasks/U-cLxfzqSQ-FJuklSkEzCA/runs/0/logs/public/logs/live.log#L417) `Skip weight & biases publication as requested by operator through WANDB_PUBLICATION`, then no wandb logs whatsoever
- However the [finetune task](https://firefox-ci-tc.services.mozilla.com/tasks/eVwiUPEdT-qpohp_Dc2J-g/definition) does not have `WANDB_PUBLICATION` set, so [it does publish on CI](https://firefox-ci-tc.services.mozilla.com/tasks/eVwiUPEdT-qpohp_Dc2J-g/runs/1/logs/public/logs/live.log).

I'm making a patch for that task
