### ISSUE TITLE
Wrong tcol when cleaning with Bicleaner

### ISSUE THREAD

**Issue by ZJaume** [mozilla/firefox-translations-training#56]
Shouldn't [this](https://github.com/mozilla/firefox-translations-training/blob/ef8928b45417a49138e2a4aad97a82282ea448f9/pipeline/bicleaner/bicleaner.sh#L39) line say `--scol 1 --tcol 2`?

**Comment by eu9ene** [comment]
Yes, it should be 2. It is a pretty critical bug, thank you!

**Comment by ZJaume** [comment]
Also realised that the next line awk command should have the tab as field separator with `-F"\t"`, right?

Thank you for your work. I've thought a lot of times in automating the training of teachers and students for my everyday work. This pipeline looks really good!

**Comment by eu9ene** [comment]
Nice catch! These two bugs together gave me the impression that something is being filtered... We should definitely test all this more thoroughly.

**Comment by eu9ene** [comment]
Another issue is that we should swap them if the bicleaner model is in the opposite direction of the trained model. I'll fix all this right away.

**Comment by ZJaume** [comment]
Yeah, `--scol 2 --tcol 1` is fine if you don't wanna swap columns.
