### ISSUE TITLE
Add an author field

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#578]
We should be able to identify the author of an experiment. Currently, it's always `moz-translations-wandb-bot` because of the service token we use. Let's find a way to either change this one or use another field.

**Comment by eu9ene** [comment]
@bhearsum I wonder if there's a way to pull a secret based on the author of the task. Then instead of using our service token we could use personal tokens to automatically identify authors in w&B.

<img width="729" alt="Screenshot 2024-05-08 at 9 48 37 AM" src="https://github.com/mozilla/firefox-translations-training/assets/2486505/58ecfb2f-5bd8-42e6-a21d-ef173b827b73">

**Comment by bhearsum** [comment]
There's no technical reason we can't do that. The secrets are defined in the task definitions: https://github.com/mozilla/firefox-translations-training/blob/c4b0d121985d84ed88aefc966df0ffbb1431a3ed/taskcluster/kinds/train-backwards/kind.yml#L70

The person who triggered the task (whether by opening a PR, making a push, or triggering an action) is available in `config.params["owner"]` in the transforms. So we could either substitute that into the secret in a transform, or add the secret entirely in a transform.

We'd likely want some way to gracefully handle the secret not existing. That could be checking for existence before adding it to the task definition (and fallback to disabling or a default), or it could be done somewhere in the payload. Eg: if the secret doesn't exist we implicitly disable publication.

**Comment by eu9ene** [comment]
Ok, ideally we should do tricks with tokens because it turned out W&B has some nice filters like "show only my work" based on this Author field and I don't see an API to override that.

**Comment by La0** [comment]
After discussion there will not be multiple tokens.

We can add a new tag on the run, with format `author:<owner>` where `<owner>`  comes from the run configuration as mentionned by @bhearsum above.

**Comment by gregtatum** [comment]
I'm happy with this solution.
