### ISSUE TITLE
[taskcluster:error] Error uploading "public/build/tmp/aln.fwd" artifact. ext.certificate.expiry < now

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#582]
New Taskcluster error: https://firefox-ci-tc.services.mozilla.com/tasks/aJKhHjeGSzmLPU7p9V8sLg/runs/10/logs/public/logs/live.log

**Comment by bhearsum** [comment]
What this _looks_ like is the artifact is taking a very, very long time to upload, so long that the credentials being used to upload it have expired. It looks like we managed to upload 2.8GB of it, and it also looks like it tracks with the overall corpus size...so presumably a large file is expected.

This is _probably_ a freak occurence for two reasons:
- It looks like we were uploading at ~2MB/sec, which is quite slow AFAIK. I assume this is just GCP gremlins.
- This happened on `docker-worker`, which AFAIK doesn't refresh its credentials.

We probably can't do anything about the first thing. We just moved these tasks (and other `docker-worker` tasks) to generic-worker in #561), which does refresh its credentials. So, even if we hit slow uploads again it _shouldn't_ cause a failure.

**Comment by eu9ene** [comment]
Another instance of this in our production run: https://firefox-ci-tc.services.mozilla.com/tasks/GhxiBn7ARVej3AUHwb9h1w

**Comment by bhearsum** [comment]
Unfortunately, I don't think there's anything tractable here other than switching to generic-worker :(

**Comment by bhearsum** [comment]
Seeing as there is nothing we can do about this directly, I'm going to close this. I opened #710 for the "fix" of switching to generic-worker.
