### ISSUE TITLE
Our models should be robust enough to translate a calendar

### ISSUE THREAD

**Issue by gregtatum** [mozilla/firefox-translations-training#600]
The models tend to break down when presented with single numbers, or lists of numbers.

For example de-en translates

```
1
2
3
4
5
6
7
8
9
```

as

```
1
2
3
4
5 5
6 6
7
8
9 9
```

While `en-ca` (which did not use opus cleaner) succeeds.

Here is an example of what calendars look like when the model can't handle this.

![screenshot of a calendar widget with normal numbers](https://github.com/mozilla/firefox-translations-training/assets/1588648/1b5757db-56ef-4767-b3de-2444df479fea)

![screenshot of a calendar widget with repeated numbers]https://github.com/mozilla/firefox-translations-training/assets/1588648/28d570fe-cc11-42f3-b7ed-d314575bc5d8)

This page is pretty useful as an in-browser test: https://www.timeanddate.com/calendar/

**Comment by gregtatum** [comment]
This could be helped by num_mismatch in OpusCleaner, and probably #215.

**Comment by eu9ene** [comment]
I see that the new models (lt-en, sl-en, sr-en, lv-en) translate numbers correctly:

<img width="1299" alt="Screenshot 2024-07-12 at 3 58 20 PM" src="https://github.com/user-attachments/assets/ab2cb541-7935-4269-832e-42df60095c1c">


Closing. Retraining existing models to use the latest improvements is a separate issue.
