### ISSUE TITLE
Use a defined run ID on W&B (refactoring)

### ISSUE THREAD

**Issue by vrigal** [mozilla/firefox-translations-training#610]
Follow-up of #595

We can eventually set a unique run ID on W&B (different than run name displayed in graphs, see #408), for example `<group>-<model_name>`.
This would allow refactor existing runs detection (actually based on display name), and simplify resuming publication to W&B (resume="allow" with a run ID [doc](https://docs.wandb.ai/guides/runs/resuming)).

**Comment by eu9ene** [comment]
Related to #601
