### ISSUE TITLE
Support COMET metric in the parser

### ISSUE THREAD

**Issue by vrigal** [mozilla/firefox-translations-training#615]
Ref. https://github.com/mozilla/firefox-translations-training/pull/598#pullrequestreview-2064482857

* Online publication (in `pipeline/eval/eval.py`)
* `.metrics` files containing 3 lines with a float value (generic method in `tracking.translations_parser.data.Metric.from_file`) - this part can be done later (less critical)

**Comment by eu9ene** [comment]
We can handle offline publication for this later
