### ISSUE TITLE
Generate a report after training is finished, and ideally ready to distribute models

### ISSUE THREAD

**Issue by XapaJIaMnu** [mozilla/firefox-translations-training#62]
After training is finished we would like to generate a report similar to this one:
https://github.com/browsermt/students/blob/master/bgen/README.md

More ideally, we would like to generate all the companion scripts so that the models are ready to be distributed to the students repo.

I understand that this is low priority, but taking models from the pipeline and arranging them for distribution takes a while.

**Comment by eu9ene** [comment]
There is a snakemake report that includes a part of this information.

A report in bergamot-students repo format is out of scope for the Mozilla training pipeline. However, if you would like to implement it and include it in this repo as a separate script, I will happily review it.

**Comment by gregtatum** [comment]
We're in a bit of a different state now. This is a great example of what information to include in our model registry. However the specific recommendation is a bit outdated, and I believe we'll re-think our entire approach.
