### ISSUE TITLE
Some mtdata datasets fail because of long name

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#654]
It's related to the Taskcluster limitation of the label size (256 characters)

Example:

```
- mtdata_ELRC-convention_against_torture_other_cruel_inhuman_or_degrading_treatment_or_punishment_united_nations-1-ell-eng
```

**Comment by bhearsum** [comment]
We should fix this by shortening the name somehow. We could run these names through some function that guarantees:
- a short enough name
- uniqueness

**Comment by bhearsum** [comment]
@eu9ene, @gregtatum - how would you feel about taking the first N characters of datasets, truncating the rest, and adding an md5 (or similar) hash of the full dataset to the end? This would keep the datasets reasonable readable and ensure uniqueness without needing to maintain some sort of lookup table.

**Comment by eu9ene** [comment]
Sounds good. I don't think the label is particularly important for training datasets. For evals, we use short dataset names.

**Comment by bhearsum** [comment]
Oh, I see we're already doing something similar after https://github.com/mozilla/firefox-translations-training/pull/611 - I'll extend that work.
