### ISSUE TITLE
Dataset deduplication issues.

### ISSUE THREAD

**Issue by XapaJIaMnu** [mozilla/firefox-translations-training#66]
We currently have 2 data backends: OpusMT and mtdata. They both seem to get the user a semi-disjoint set of datasets, and on top of that, those in mtdata are more up-to-date. Some of the really big ones are duplicated (Hello CC-Aligned) and some of the small ones (ELRC ones) are outdated in OpusMT.

Unfortunately due to datasets being named differently, and having so many of them, it's difficult for non-MT people to filter duplicates. On top of that some datasets have different versions (like paracrawl) where only the latest should be used, but other datasets (like news-commentary) contain unique data in every version.

Checksumming as mentioned in #60 might be a way to prevent some of the duplicated datasets from being used during training, but it will not take care of the versioning issue.

Those are a lot, and complicated issues. I think the best solution would be to work with upstream data fetcher developers (be it mtdata and opus) and try to get some (or all) of those constraints in their code.

**Comment by gregtatum** [comment]
We have `task find-corpus` these days, which provides a nice summary of available datasets, and data de-duplicating in the pipeline.
