### ISSUE TITLE
Teacher training regression

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#669]
I see a super weird major regression in teacher training quality after the [fix](https://github.com/mozilla/firefox-translations-training/pull/658) of the Sacrebleu importer in the release branch.

The configs for uk-en were identical, moreover sacrebleu is not used in dev/test datasets, so there's no reason for it to regress. I see the same for the other restarted models: cs-en, el-en, ro-en, sk-en. COMET evals are ~0.5 (meaning garbage) for all of them.

[Proper training uk-en train action](https://firefox-ci-tc.services.mozilla.com/tasks/YKY97vZVTdODzmzG0q6rAA)
[Regressed train action](https://firefox-ci-tc.services.mozilla.com/tasks/Tat9yj5WT3mxcPNgI8PW5Q)

[Proper training run](https://firefox-ci-tc.services.mozilla.com/tasks/fENJrS54TlO8d1A8FXZKyQ/runs/0/logs/public/logs/live.log)
[Regressed run](https://firefox-ci-tc.services.mozilla.com/tasks/Rmx1-mEcTRKBxNEYZaA1ww/runs/0/logs/public/logs/live.log)

<img width="2269" alt="Screenshot 2024-06-11 at 1 45 24 PM" src="https://github.com/mozilla/firefox-translations-training/assets/2486505/20c2ffb0-f45d-4e01-85b9-a1461f125d73">

@bhearsum @gabrielBusta I wonder if it can be somehow related to infrastructure. Did we implement any changes on infra level  recently that might affect the release branch?

**Comment by eu9ene** [comment]
I reran `uk-en` from the same decision task as the proper training run and it follows the path of the wrong one: https://firefox-ci-tc.services.mozilla.com/tasks/V4SL4XEWS6SM1eM8kPiqjw/runs/0.

I found differences in train logs:

```
 ### Number of empty alignments for /home/ubuntu/tasks/task_id/fetches/mono.aln.zst: 162528702
```
vs
```
 ### Number of empty alignments for /home/ubuntu/tasks/task_id/fetches/mono.aln.zst: 2555
```
So for the incorrect training, almost all the alignments for back-translations are empty which means OpusTrainer will skip those examples.

@gabrielBusta so, you changed the machine `b-cpu-xlargedisk` for alignments, right? Were there any changes in the environment of the machine? OS, Docker image etc.

**Comment by eu9ene** [comment]
I see that eflomal has some C++ code that might behave differently in a different system environment https://github.com/robertostling/eflomal/tree/master/src

**Comment by gabrielBusta** [comment]
That is so strange. I did change `b-cpu-xlargedisk`. I added more RAM (and the required CPUs to support it.) Then terminated the workers. I don't see how that would affect the number of empty alignments 👀

**Comment by gabrielBusta** [comment]
Maybe it's related to #658? Seems suspicious that the regression started after that landed

**Comment by eu9ene** [comment]
No, I reran the uk-en pair from the same train action as the first run without the sacrebleu fix and I see the same incorrect behavior because now it uses the newly produced alignments. And this happened for all languages that were launched after the fix I think.

**Comment by gabrielBusta** [comment]
[Bug 1902080: Refactor translations b-linux-large-gcp-1tb worker pools to allow for experimentation with different configurations](https://bugzilla.mozilla.org/show_bug.cgi?id=1902080)

**Comment by eu9ene** [comment]
update: the issue is in the back-translated data. The teacher used merge-mono artifacts from [this task group](https://firefox-ci-tc.services.mozilla.com/tasks/groups/FZ-qmI7HSjyDeCOeJAWJBA) but it should have been scheduled in [the new task group](https://firefox-ci-tc.services.mozilla.com/tasks/groups/Tat9yj5WT3mxcPNgI8PW5Q) after retraining the backward model was retrained.

**Comment by eu9ene** [comment]
ok, the next hypothesis is that the new machine has affected the sorting behaviour in `translate/collect.sh` script:

I attached to `collect-mono-trg` task and tried the code there, so it sorts incorrectly which results in an incorrect merging of translated texts. We had this issue before and fixed it with this new code.

```
root@6d9ffc892259:~/fetches# find . -name '*.out.zst' | sort -t '.' -k2,2n
./file.10.out.zst
./file.11.out.zst
./file.12.out.zst
./file.13.out.zst
./file.14.out.zst
./file.15.out.zst
./file.16.out.zst
./file.17.out.zst
./file.18.out.zst
./file.19.out.zst
./file.1.out.zst
./file.20.out.zst
./file.2.out.zst
./file.3.out.zst
./file.4.out.zst
./file.5.out.zst
./file.6.out.zst
./file.7.out.zst
./file.8.out.zst
./file.9.out.zst
```

**Comment by bhearsum** [comment]
For the record, nothing changed about the OS - we use the _exact_ same image as we did with fewer CPUs. The CPU type also didn't change. The only thing we did was add more CPUs and RAM. (If there's any code that parallelizes across cores I guess I could imagine this theoretically being able to influence behaviour.)

**Comment by eu9ene** [comment]
Ok, I actually tested it incorrectly. This gives me the correct sorting, so it's probably something else:

```
export chunks_dir=fetches
find "${chunks_dir}" -name '*.out.zst' | sort -t '.' -k2,2n
fetches/file.1.out.zst
fetches/file.2.out.zst
fetches/file.3.out.zst
fetches/file.4.out.zst
fetches/file.5.out.zst
fetches/file.6.out.zst
fetches/file.7.out.zst
fetches/file.8.out.zst
fetches/file.9.out.zst
fetches/file.10.out.zst
fetches/file.11.out.zst
fetches/file.12.out.zst
fetches/file.13.out.zst
fetches/file.14.out.zst
fetches/file.15.out.zst
fetches/file.16.out.zst
fetches/file.17.out.zst
fetches/file.18.out.zst
fetches/file.19.out.zst
fetches/file.20.out.zst
```

But the fact is that the sentences in [collect-mono-trg](https://firefox-ci-tc.services.mozilla.com/tasks/A1kkCXXpRWiB_8lk-M6xHA) and [merge-mono-trg](https://firefox-ci-tc.services.mozilla.com/tasks/Jesh4f3VTuipgyNE7bvzNQ) are not properly aligned, so it's basically noise. This explains the behavior of the aligner and teacher training.

**Comment by eu9ene** [comment]
Ok, I think I know what's going on. Let's look at the task graph of the failed task group: train-teacher and alignments-backtranslated depend on one [merge-mono-trg task](https://firefox-ci-tc.services.mozilla.com/tasks/Jesh4f3VTuipgyNE7bvzNQ) but if we go from collect-mono-trg -> translate -> [split-mono-trg](https://firefox-ci-tc.services.mozilla.com/tasks/dPd84f3SSBOEtwU16cb1Aw) it depends on another [merge-mono-trg task](https://firefox-ci-tc.services.mozilla.com/tasks/XaDIm1B9TgiEuPLD5miO6Q). This happens because our target mono dataset is the same for all xx-en runs and is shared across all task groups. The issue is that if we run several trainings simultaneously, we get multiple different mono en tasks and I guess the latest overrides the cache. Check out this [funny graph](https://gregtatum.github.io/taskcluster-tools/?taskGroupIds=Tat9yj5WT3mxcPNgI8PW5Q&fetchDependentTasks=true&mergeChunks=true).

**Comment by bhearsum** [comment]
> Ok, I think I know what's going on. Let's look at the task graph of the failed task group: train-teacher and alignments-backtranslated depend on one [merge-mono-trg task](https://firefox-ci-tc.services.mozilla.com/tasks/Jesh4f3VTuipgyNE7bvzNQ) but if we go from collect-mono-trg -> translate -> [split-mono-trg](https://firefox-ci-tc.services.mozilla.com/tasks/dPd84f3SSBOEtwU16cb1Aw) it depends on another [merge-mono-trg task](https://firefox-ci-tc.services.mozilla.com/tasks/XaDIm1B9TgiEuPLD5miO6Q). This happens because our target mono dataset is the same for all xx-en runs and is shared across all task groups. The issue is that if we run several trainings simultaneously, we get multiple different mono en tasks and I guess the latest overrides the cache. Check out this [funny graph](https://gregtatum.github.io/taskcluster-tools/?taskGroupIds=Tat9yj5WT3mxcPNgI8PW5Q&fetchDependentTasks=true&mergeChunks=true).

It sounds like we should probably add the src+trg information to the cache resources in this case. Eg: a `from-parameters` section in https://github.com/mozilla/firefox-translations-training/blob/fd2f7da7a47eaeb9dde92a47f250afb000edb465/taskcluster/kinds/merge-mono/kind.yml#L25 similar to https://github.com/mozilla/firefox-translations-training/blob/fd2f7da7a47eaeb9dde92a47f250afb000edb465/taskcluster/kinds/translate-corpus/kind.yml#L38-L40.

Or we could make sure the src+trg is included in the label.

**Comment by bhearsum** [comment]
It looks like we previously had src+trg in the label, but it was removed in https://github.com/mozilla/firefox-translations-training/commit/be065b5465199984da48562ba17ebd585667b0eb#diff-ed01a886331a09bef4a6ef2bef2ca8ed8b721579d5cd7e33316b68a2f2b7a0e8, fwiw.

**Comment by eu9ene** [comment]
The idea was to reuse the cache for mono tasks and it's working but the issue here is that `merge-mono` is not deterministic because it includes data shuffling. Basically having the same inputs gives you different results. Otherwise, this would work. If we add src and trg as cache keys we still can hit this issue by running two uk-en train runs at the same time. Another workaround would be to use a random seed to make the shuffling deterministic.

**Comment by eu9ene** [comment]
I made shuffling deterministic, so closing this
