### ISSUE TITLE
Quality of teacher model degraded for Russian

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#71]
I trained ru-en model with broken bicleaner and ce-mean-wrods as a stopping criteria and another one with fixed bicleaner and chrf per our latest recipe. The models were trained and evaluated on the same dataset.

Quality got worse and we need to investigate why.

### With broken bicleaner and ce-mean-words as the first metric (early stop on ce-mean-words stalled 10 times)

pre-training stops after 2 epochs by default

teacher pretrained 0

`[data] Done shuffling 223,714,656 sentences (cached in RAM)`
`[valid] Ep. 3 : Up. 213503 : bleu-detok : 39.4599 : new best`

teacher pretrained 1
`[data] Done shuffling 223,714,656 sentences (cached in RAM)`
`[valid] Ep. 3 : Up. 213554 : bleu-detok : 39.5594 : stalled 2 times (last best: 39.5754)`

teacher fine-tuned 0
`[data] Done shuffling 203,714,656 sentences (cached in RAM)`
`[valid] Ep. 11 : Up. 996000 : bleu-detok : 40.2673 : stalled 16 times (last best: 40.3048)`
teacher fine-tuned 1 - wasn't trained

### With fixed bicleaner and chrf as the first metric 

teacher pretrained 0 ( I had to increase early stopping because I got smth like 38.5 after 2 epochs, assuming there's less data now)
`Done shuffling 176,961,018 sentences`
`[valid] Ep. 5 : Up. 825000 : bleu-detok : 39.7754 : stalled 8 times (last best: 39.8173)`

teacher pretrained 1
`Done shuffling 176,961,018 sentences`
`Ep. 5 : Up. 771000 : bleu-detok : 39.7417 : stalled 20 times (last best: 39.8469)`

teacher fine-tuned 0
`[data] Done shuffling 156,961,018 sentences (cached in RAM)`
`[valid] Ep. 1 : Up. 33000 : bleu-detok : 38.6797 : stalled 10 times (last best: 39.3428)`

teacher fine-tuned 1
`[data] Done shuffling 156,961,018 sentences (cached in RAM)`
`[valid] Ep. 1 : Up. 33000 : bleu-detok : 38.7464 : stalled 10 times (last best: 39.3711)`

It seems I also should increase patience here, but it's early stopping 10 by default. Should we change the recipe?

Another hypothesis is that bicleaner filters way too much. I used these thresholds:

```
  bicleaner:
    default-threshold: 0.5
    dataset-thresholds:
      opus_CCAligned/v1: 0.7
      opus_WikiMatrix/v1: 0.7
      opus_OpenSubtitles/v2018: 0.8
      opus_bible-uedin/v1: 0.7
      mtdata_cc_aligned: 0.7
      mtdata_wiki_titles_v1: 0.7
      mtdata_WikiMatrix_v1: 0.7
      mtdata_wiki_titles_v2: 0.7
      mtdata_wmt13_commoncrawl: 0.7
      # 0 = skip filtering
      opus_ParaCrawl/v8: 0
      custom-corpus_/data/rw/home/corpus/ru-en/ParaCrawl-paracrawl-1_bonus-eng-rus: 0
```
I tuned manually only opus_OpenSubtitles one, but it's pretty subjective. Probably I should go through all datasets and inspect them visually which is time-consuming. Maybe we can come up with some thresholds from other training experiences?

Filtering results:

```
./mtdata_wmt18_news_commentary_v13.log:+ echo 'Lines before filtering: 214390'
./mtdata_wmt18_news_commentary_v13.log:+ echo 'Lines after filtering: 190257'
./opus_TED2013/v1.1.log:+ echo 'Lines before filtering: 127928'
./opus_TED2013/v1.1.log:+ echo 'Lines after filtering: 103933'
./opus_GlobalVoices/v2018q4.log:+ echo 'Lines before filtering: 155118'
./opus_GlobalVoices/v2018q4.log:+ echo 'Lines after filtering: 123586'
./opus_EUbookshop/v2.log:+ echo 'Lines before filtering: 39089'
./opus_EUbookshop/v2.log:+ echo 'Lines after filtering: 23929'
./opus_UNPC/v1.0.log:+ echo 'Lines before filtering: 22106825'
./opus_UNPC/v1.0.log:+ echo 'Lines after filtering: 18503319'
./opus_CCAligned/v1.log:+ echo 'Lines before filtering: 11527234'
./opus_CCAligned/v1.log:+ echo 'Lines after filtering: 4839631'
./opus_Books/v1.log:+ echo 'Lines before filtering: 16422'
./opus_Books/v1.log:+ echo 'Lines after filtering: 9857'
./opus_wikimedia/v20210402.log:+ echo 'Lines before filtering: 277000'
./opus_wikimedia/v20210402.log:+ echo 'Lines after filtering: 200850'
./opus_Ubuntu/v14.10.log:+ echo 'Lines before filtering: 4186'
./opus_Ubuntu/v14.10.log:+ echo 'Lines after filtering: 2514'
./opus_OpenSubtitles/v2018.log:+ echo 'Lines before filtering: 22336570'
./opus_OpenSubtitles/v2018.log:+ echo 'Lines after filtering: 2442561'
./opus_tico-19/v2020-10-28.log:+ echo 'Lines before filtering: 3058'
./opus_tico-19/v2020-10-28.log:+ echo 'Lines after filtering: 2913'
./opus_infopankki/v1.log:+ echo 'Lines before filtering: 67361'
./opus_infopankki/v1.log:+ echo 'Lines after filtering: 48444'
./mtdata_neulab_tedtalksv1_dev.log:+ echo 'Lines before filtering: 4667'
./mtdata_neulab_tedtalksv1_dev.log:+ echo 'Lines after filtering: 2208'
./opus_XLEnt/v1.1.log:+ echo 'Lines before filtering: 3790416'
./opus_XLEnt/v1.1.log:+ echo 'Lines after filtering: 1295583'
./opus_News-Commentary/v16.log:+ echo 'Lines before filtering: 253633'
./opus_News-Commentary/v16.log:+ echo 'Lines after filtering: 229244'
./mtdata_czechtourism.log:+ echo 'Lines before filtering: 7028'
./mtdata_czechtourism.log:+ echo 'Lines after filtering: 5488'
./opus_PHP/v1.log:+ echo 'Lines before filtering: 5752'
./opus_PHP/v1.log:+ echo 'Lines after filtering: 739'
./mtdata_neulab_tedtalksv1_test.log:+ echo 'Lines before filtering: 5305'
./mtdata_neulab_tedtalksv1_test.log:+ echo 'Lines after filtering: 2548'
./opus_MultiUN/v1.log:+ echo 'Lines before filtering: 10468452'
./opus_MultiUN/v1.log:+ echo 'Lines after filtering: 9018564'
./mtdata_wmt13_commoncrawl.log:+ echo 'Lines before filtering: 697615'
./mtdata_wmt13_commoncrawl.log:+ echo 'Lines after filtering: 287068'
./opus_CCMatrix/v1.log:+ echo 'Lines before filtering: 137563345'
./opus_CCMatrix/v1.log:+ echo 'Lines after filtering: 119035196'
./opus_TED2020/v1.log:+ echo 'Lines before filtering: 373193'
./opus_TED2020/v1.log:+ echo 'Lines after filtering: 270586'
./opus_QED/v2.0a.log:+ echo 'Lines before filtering: 487300'
./opus_QED/v2.0a.log:+ echo 'Lines after filtering: 362346'
./mtdata_JW300.log:+ echo 'Lines before filtering: 865388'
./mtdata_JW300.log:+ echo 'Lines after filtering: 540475'
./opus_Tatoeba/v2021-03-10.log:+ echo 'Lines before filtering: 512920'
./opus_Tatoeba/v2021-03-10.log:+ echo 'Lines after filtering: 472130'
./mtdata_wiki_titles_v1.log:+ echo 'Lines before filtering: 585872'
./mtdata_wiki_titles_v1.log:+ echo 'Lines after filtering: 94476'
./opus_ELRC_2922/v1.log:+ echo 'Lines before filtering: 3868'
./opus_ELRC_2922/v1.log:+ echo 'Lines after filtering: 3336'
./mtdata_neulab_tedtalksv1_train.log:+ echo 'Lines before filtering: 202473'
./mtdata_neulab_tedtalksv1_train.log:+ echo 'Lines after filtering: 161368'
./opus_Tanzil/v1.log:+ echo 'Lines before filtering: 887456'
./opus_Tanzil/v1.log:+ echo 'Lines after filtering: 328163'
./opus_ada83/v1.log:+ echo 'Lines before filtering: 4050'
./opus_ada83/v1.log:+ echo 'Lines after filtering: 3541'
./opus_Wikipedia/v1.0.log:+ echo 'Lines before filtering: 427786'
./opus_Wikipedia/v1.0.log:+ echo 'Lines after filtering: 311595'
./opus_KDE4/v2.log:+ echo 'Lines before filtering: 114288'
./opus_KDE4/v2.log:+ echo 'Lines after filtering: 53569'
./mtdata_worldbank.log:+ echo 'Lines before filtering: 25278'
./mtdata_worldbank.log:+ echo 'Lines after filtering: 23039'
./opus_WikiMatrix/v1.log:+ echo 'Lines before filtering: 1520248'
./opus_WikiMatrix/v1.log:+ echo 'Lines after filtering: 739585'
./opus_GNOME/v1.log:+ echo 'Lines before filtering: 103'
./opus_GNOME/v1.log:+ echo 'Lines after filtering: 24'
./opus_UN/v20090831.log:+ echo 'Lines before filtering: 69518'
./opus_UN/v20090831.log:+ echo 'Lines after filtering: 63322'
./opus_bible-uedin/v1.log:+ echo 'Lines before filtering: 60980'
./opus_bible-uedin/v1.log:+ echo 'Lines after filtering: 2334'
./mtdata_wiki_titles_v2.log:+ echo 'Lines before filtering: 630623'
./mtdata_wiki_titles_v2.log:+ echo 'Lines after filtering: 101764'
./opus_TildeMODEL/v2018.log:+ echo 'Lines before filtering: 9451'
./opus_TildeMODEL/v2018.log:+ echo 'Lines after filtering: 7087'
./mtdata_airbaltic.log:+ echo 'Lines before filtering: 1033'
./mtdata_airbaltic.log:+ echo 'Lines after filtering: 840'
```

**Comment by eu9ene** [comment]
@kpu @XapaJIaMnu please take a look, we need to figure out how to fix it

**Comment by kpu** [comment]
Bicleaning everything is a bad idea because it will throw out all short sentences and the system won't know how to translate short stuff, which occur frequently on the web.  As a rough heuristic, if bicleaner isn't throwing out much, it probably shouldn't be run on the corpus.  

Russian isn't one of the well-maintained releases of paracrawl and was cleaned with an old version of bicleaner.  It should probably be recleaned from raw data (and even a new release just doing that).  

@ZJaume is the model well-tested for Russian?  Or is the only Cyrillic it knows about Bulgarian?  I suspect #55 would be better here.  

I'd inspect the UN corpora for tokenization and make sure they're getting detokenized properly.  Same with world bank.  JW300 should be being fixed by the scripts, right?  

Deduplicate versions of corpora.  For instance, I see two versions of paracrawl and two versions of wiki titles.  Should only use the most recent wiki titles.  (Ultimately we should write some rules for this that semi-automatically select corpora for a language, but it's manual for now.)

Opensubtitles cleaning seems overly harsh.  It's noisy but not that noisy.  Something odd is going on there.

**Comment by kpu** [comment]
Also this is in WMT: https://translate.yandex.ru/corpus?lang=en .  How angry would it make the lawyers?

**Comment by XapaJIaMnu** [comment]
I see that your training finished before going through one full loop of the data and there are duplicated datasets. It is entirely possible that the model finishes training before ever seeing some of the data. Also, as kenneth mentioned the cleaning of some files is overly harsh. CCAligned is left with less than half of its data. Bicleaner thresholds might need to be tweaked.

**Comment by kpu** [comment]
> I see that your training finished before going through one full loop of the data

@XapaJIaMnu It says epoch 5.  The epoch 1 was fine tuning.

**Comment by kpu** [comment]
Wait a sec. . . the teachers are better now right?  

Before: 39.4599 39.5754

Now: 39.8173 39.8469

It's fine tuning that's broken.  What are you fine tuning and validating on?

**Comment by eu9ene** [comment]
pre-training: training on parallel+backtranslated datasets
fine-tuning: finetuning a pre-trained model on a parallel dataset only

I'm sure there's a lot to improve, but I'm trying to understand what's the difference between two runs on the same datasets. 

I don't have logs from my first attempt to pre-train on just two epochs but the quality was lower than without bicleaner (smth like 38.5 vs 39.5), that's why I increased patience and trained longer (for 5 epochs).

There is deduplication of sentences on merging, so I'm not worried about the same paracrawl being used twice.

So the plan to fix this would be:
1. Lower bicleaner thresholds:
  - What thresholds to use and when to skip bicleaner entirely? 
  - Are thresholds really language/corpus dependant or we should use just recommended 0.5? 
  - What maximum percentage of corpus should we aim to filter? 
  - Who can provide recommended thresholds for different datasets?
2. Change the recipe to use different patience for chrf. Any suggestions?
3. Should I limit pre-training to N sentences (or batches) instead of epochs? I didn't come up with a good number, that's why I used epochs. How many sentences should be enough?

Overall we need something more reproducible with good enough defaults to handle a wide range of languages. I understand that there's a lot of room for improvement for each specific language.

**Comment by ZJaume** [comment]
> @ZJaume is the model well-tested for Russian? Or is the only Cyrillic it knows about Bulgarian?

It's not well tested, unfortunately.

> I suspect #55 would be better here.

Yes indeed.

> * What thresholds to use and when to skip bicleaner entirely?

I think what it is being more problematic here is hardrules. That is because hardrules is really focused on cleaning web-crawled and not optimized at all for scenarios like this. If it's causing issues, my advice would be one of this options:
1. Given that you are using clean scripts from the students repo, leave those ones as the heuristic filtering and disable hardrules. I've been using the clean scripts with bicleaner only with the classifier and has worked well.
2. Use [bicleaner-hardrules](https://github.com/bitextor/bicleaner-hardrules) master branch that has config interface to enable/disable each rule individually and disable the most problematic ones.
   * The current published versions of bicleaner only let user to disable minimal length, langid and lm_filter.
   * You can run `bicleaner-hardrules` with `--annotated_output` and sort count to see which ones are throwing more sentence pairs.

> * Are thresholds really language/corpus dependant or we should use just recommended 0.5?

It's quite probable, specially in the old bicleaner. It uses statistical features that impact a lot on threshold and the training data for the classifier are corpora from opus. So, scoring corpora from those sources can probably cause the scores to be higher (this can also happen on bicleaner-ai but less).

If you really need to forget about the threshold, bicleaner-ai full models tend to be less dependant of the threshold. The 90% of the scored sentences are usually in 0.0-0.1 and 0.9-1.0 ranges, and it's pretty accurate.

We won't plan to publish bicleaner-ai for Russian soon, but train a full model by yourself could be another good option. You only need 300K-500K clean sentences.

> * Who can provide recommended thresholds for different datasets

I don't have one.

**Comment by eu9ene** [comment]
> > I suspect https://github.com/mozilla/firefox-translations-training/issues/55 would be better here.

> Yes indeed.

@ZJaume so, do you recommend not using the regular bicleaner at all and using multilingual bicleaner-ai model for unsupported languages like Russian?

**Comment by ZJaume** [comment]
> @ZJaume so, do you recommend not using the regular bicleaner at all and using multilingual bicleaner-ai model for unsupported languages like Russian?

I think that Russian is the only case where we have Bicleaner model and not Bicleaner AI model, but yes I do recommend.

**Comment by eu9ene** [comment]
I completed filtering for Russian using bicleaner-ai full multilingual model and it looks too aggressive.

I noticed that even if one word from a long sentence is not translated precisely (for example a name) it can assign 0 score.
There are just 45M sentences left in the parallel corpus. I can try to retrain on this corpus including the backward model and augmentation but I suspect having 4 times more but slightly noisier data is better.  

```
    default-threshold: 0.5
    dataset-thresholds:
      opus_CCAligned/v1: 0.6
      opus_WikiMatrix/v1: 0.6
      opus_OpenSubtitles/v2018: 0.7
      opus_bible-uedin/v1: 0.6
      mtdata_cc_aligned: 0.6
      mtdata_wiki_titles_v1: 0.6
      mtdata_WikiMatrix_v1: 0.6
      mtdata_wiki_titles_v2: 0.6
      mtdata_wmt13_commoncrawl: 0.6
```
```

./mtdata_wmt18_news_commentary_v13.log:+ echo 'Lines before filtering: 214390'
./mtdata_wmt18_news_commentary_v13.log:+ echo 'Lines after filtering: 36368'
./opus_TED2013/v1.1.log:+ echo 'Lines before filtering: 127928'
./opus_TED2013/v1.1.log:+ echo 'Lines after filtering: 18574'
./opus_GlobalVoices/v2018q4.log:+ echo 'Lines before filtering: 155118'
./opus_GlobalVoices/v2018q4.log:+ echo 'Lines after filtering: 30148'
./opus_EUbookshop/v2.log:+ echo 'Lines before filtering: 39089'
./opus_EUbookshop/v2.log:+ echo 'Lines after filtering: 7303'
./opus_UNPC/v1.0.log:+ echo 'Lines before filtering: 22106825'
./opus_UNPC/v1.0.log:+ echo 'Lines after filtering: 5128502'
./opus_CCAligned/v1.log:+ echo 'Lines before filtering: 11527234'
./opus_CCAligned/v1.log:+ echo 'Lines after filtering: 2670034'
./opus_Books/v1.log:+ echo 'Lines before filtering: 16422'
./opus_Books/v1.log:+ echo 'Lines after filtering: 2251'
./opus_wikimedia/v20210402.log:+ echo 'Lines before filtering: 277000'
./opus_wikimedia/v20210402.log:+ echo 'Lines after filtering: 59638'
./opus_Ubuntu/v14.10.log:+ echo 'Lines before filtering: 4186'
./opus_Ubuntu/v14.10.log:+ echo 'Lines after filtering: 1467'
./opus_OpenSubtitles/v2018.log:+ echo 'Lines before filtering: 22336570'
./opus_OpenSubtitles/v2018.log:+ echo 'Lines after filtering: 6645747'
./opus_tico-19/v2020-10-28.log:+ echo 'Lines before filtering: 3058'
./opus_tico-19/v2020-10-28.log:+ echo 'Lines after filtering: 750'
./opus_infopankki/v1.log:+ echo 'Lines before filtering: 67361'
./opus_infopankki/v1.log:+ echo 'Lines after filtering: 12889'
./mtdata_neulab_tedtalksv1_dev.log:+ echo 'Lines before filtering: 4667'
./mtdata_neulab_tedtalksv1_dev.log:+ echo 'Lines after filtering: 713'
./opus_XLEnt/v1.1.log:+ echo 'Lines before filtering: 3790416'
./opus_XLEnt/v1.1.log:+ echo 'Lines after filtering: 464332'
./opus_News-Commentary/v16.log:+ echo 'Lines before filtering: 253633'
./opus_News-Commentary/v16.log:+ echo 'Lines after filtering: 43525'
./mtdata_czechtourism.log:+ echo 'Lines before filtering: 7028'
./mtdata_czechtourism.log:+ echo 'Lines after filtering: 1178'
./opus_PHP/v1.log:+ echo 'Lines before filtering: 5752'
./opus_PHP/v1.log:+ echo 'Lines after filtering: 253'
./mtdata_neulab_tedtalksv1_test.log:+ echo 'Lines before filtering: 5305'
./mtdata_neulab_tedtalksv1_test.log:+ echo 'Lines after filtering: 756'
./opus_MultiUN/v1.log:+ echo 'Lines before filtering: 10468452'
./opus_MultiUN/v1.log:+ echo 'Lines after filtering: 2453722'
./mtdata_wmt13_commoncrawl.log:+ echo 'Lines before filtering: 697615'
./mtdata_wmt13_commoncrawl.log:+ echo 'Lines after filtering: 93194'
./opus_CCMatrix/v1.log:+ echo 'Lines before filtering: 137563345'
./opus_CCMatrix/v1.log:+ echo 'Lines after filtering: 26205348'
./opus_TED2020/v1.log:+ echo 'Lines before filtering: 373193'
./opus_TED2020/v1.log:+ echo 'Lines after filtering: 53968'
./opus_QED/v2.0a.log:+ echo 'Lines before filtering: 487300'
./opus_QED/v2.0a.log:+ echo 'Lines after filtering: 93782'
./mtdata_JW300.log:+ echo 'Lines before filtering: 865388'
./mtdata_JW300.log:+ echo 'Lines after filtering: 137913'
./opus_Tatoeba/v2021-03-10.log:+ echo 'Lines before filtering: 512920'
./opus_Tatoeba/v2021-03-10.log:+ echo 'Lines after filtering: 267938'
./mtdata_wiki_titles_v1.log:+ echo 'Lines before filtering: 585872'
./mtdata_wiki_titles_v1.log:+ echo 'Lines after filtering: 132244'
./opus_ELRC_2922/v1.log:+ echo 'Lines before filtering: 3868'
./opus_ELRC_2922/v1.log:+ echo 'Lines after filtering: 966'
./mtdata_neulab_tedtalksv1_train.log:+ echo 'Lines before filtering: 202473'
./mtdata_neulab_tedtalksv1_train.log:+ echo 'Lines after filtering: 29621'
./custom-corpus_/data/rw/home/corpus/ru-en/ParaCrawl-paracrawl-1_bonus-eng-rus.log:+ echo 'Lines before filtering: 4916885'
./custom-corpus_/data/rw/home/corpus/ru-en/ParaCrawl-paracrawl-1_bonus-eng-rus.log:+ echo 'Lines after filtering: 831785'
./opus_Tanzil/v1.log:+ echo 'Lines before filtering: 887456'
./opus_Tanzil/v1.log:+ echo 'Lines after filtering: 98859'
./opus_ada83/v1.log:+ echo 'Lines before filtering: 4050'
./opus_ada83/v1.log:+ echo 'Lines after filtering: 1231'
./opus_Wikipedia/v1.0.log:+ echo 'Lines before filtering: 427786'
./opus_Wikipedia/v1.0.log:+ echo 'Lines after filtering: 88344'
./opus_KDE4/v2.log:+ echo 'Lines before filtering: 114288'
./opus_KDE4/v2.log:+ echo 'Lines after filtering: 29680'
./mtdata_worldbank.log:+ echo 'Lines before filtering: 25278'
./mtdata_worldbank.log:+ echo 'Lines after filtering: 5243'
./opus_WikiMatrix/v1.log:+ echo 'Lines before filtering: 1520248'
./opus_WikiMatrix/v1.log:+ echo 'Lines after filtering: 335185'
./opus_GNOME/v1.log:+ echo 'Lines before filtering: 103'
./opus_GNOME/v1.log:+ echo 'Lines after filtering: 12'
./opus_UN/v20090831.log:+ echo 'Lines before filtering: 69518'
./opus_UN/v20090831.log:+ echo 'Lines after filtering: 18555'
./opus_bible-uedin/v1.log:+ echo 'Lines before filtering: 60980'
./opus_bible-uedin/v1.log:+ echo 'Lines after filtering: 5801'
./mtdata_wiki_titles_v2.log:+ echo 'Lines before filtering: 630623'
./mtdata_wiki_titles_v2.log:+ echo 'Lines after filtering: 143911'
./opus_TildeMODEL/v2018.log:+ echo 'Lines before filtering: 9451'
./opus_TildeMODEL/v2018.log:+ echo 'Lines after filtering: 1520'
./mtdata_airbaltic.log:+ echo 'Lines before filtering: 1033'
./mtdata_airbaltic.log:+ echo 'Lines after filtering: 192'
```

**Comment by ZJaume** [comment]
Oh! that's probably my fault. I should have explained that the multilingual model must run with `--disabled-hardrules` because the language identification and other rules that are language dependent receive `xx` as langcode. When a sentence is being discarded by the hardrules or one side is empty, it gets an integer `0`. Then, if the score is a `0.000` it is because it goes through the hardrules and the classifier gives that score. You are probably discarding that much sentences because of hardrules, please disable them.

**Comment by eu9ene** [comment]
Thanks, I'll repeat the experiment with `--disabled-hardrules` flag.

**Comment by eu9ene** [comment]
It looks way better now. Corpus size is 175M sentences compared to 45M with enabled hard rules.

```
./mtdata_wmt18_news_commentary_v13.log:+ echo 'Lines before filtering: 214390'
./mtdata_wmt18_news_commentary_v13.log:+ echo 'Lines after filtering: 201502'
./opus_TED2013/v1.1.log:+ echo 'Lines before filtering: 127928'
./opus_TED2013/v1.1.log:+ echo 'Lines after filtering: 113649'
./opus_GlobalVoices/v2018q4.log:+ echo 'Lines before filtering: 155118'
./opus_GlobalVoices/v2018q4.log:+ echo 'Lines after filtering: 141723'
./opus_EUbookshop/v2.log:+ echo 'Lines before filtering: 39089'
./opus_EUbookshop/v2.log:+ echo 'Lines after filtering: 27690'
./opus_UNPC/v1.0.log:+ echo 'Lines before filtering: 22106825'
./opus_UNPC/v1.0.log:+ echo 'Lines after filtering: 20712776'
./opus_CCAligned/v1.log:+ echo 'Lines before filtering: 11527234'
./opus_CCAligned/v1.log:+ echo 'Lines after filtering: 9435774'
./opus_Books/v1.log:+ echo 'Lines before filtering: 16422'
./opus_Books/v1.log:+ echo 'Lines after filtering: 13885'
./opus_wikimedia/v20210402.log:+ echo 'Lines before filtering: 277000'
./opus_wikimedia/v20210402.log:+ echo 'Lines after filtering: 237211'
./opus_Ubuntu/v14.10.log:+ echo 'Lines before filtering: 4186'
./opus_Ubuntu/v14.10.log:+ echo 'Lines after filtering: 3752'
./opus_OpenSubtitles/v2018.log:+ echo 'Lines before filtering: 22336570'
./opus_OpenSubtitles/v2018.log:+ echo 'Lines after filtering: 16600716'
./opus_tico-19/v2020-10-28.log:+ echo 'Lines before filtering: 3058'
./opus_tico-19/v2020-10-28.log:+ echo 'Lines after filtering: 2976'
./opus_infopankki/v1.log:+ echo 'Lines before filtering: 67361'
./opus_infopankki/v1.log:+ echo 'Lines after filtering: 58557'
./mtdata_neulab_tedtalksv1_dev.log:+ echo 'Lines before filtering: 4667'
./mtdata_neulab_tedtalksv1_dev.log:+ echo 'Lines after filtering: 4359'
./opus_XLEnt/v1.1.log:+ echo 'Lines before filtering: 3790416'
./opus_XLEnt/v1.1.log:+ echo 'Lines after filtering: 1848166'
./opus_News-Commentary/v16.log:+ echo 'Lines before filtering: 253633'
./opus_News-Commentary/v16.log:+ echo 'Lines after filtering: 238556'
./mtdata_czechtourism.log:+ echo 'Lines before filtering: 7028'
./mtdata_czechtourism.log:+ echo 'Lines after filtering: 6264'
./opus_PHP/v1.log:+ echo 'Lines before filtering: 5752'
./opus_PHP/v1.log:+ echo 'Lines after filtering: 2234'
./mtdata_neulab_tedtalksv1_test.log:+ echo 'Lines before filtering: 5305'
./mtdata_neulab_tedtalksv1_test.log:+ echo 'Lines after filtering: 4905'
./opus_MultiUN/v1.log:+ echo 'Lines before filtering: 10468452'
./opus_MultiUN/v1.log:+ echo 'Lines after filtering: 9649508'
./mtdata_wmt13_commoncrawl.log:+ echo 'Lines before filtering: 697615'
./mtdata_wmt13_commoncrawl.log:+ echo 'Lines after filtering: 514714'
./opus_CCMatrix/v1.log:+ echo 'Lines before filtering: 137563345'
./opus_CCMatrix/v1.log:+ echo 'Lines after filtering: 119250143'
./opus_TED2020/v1.log:+ echo 'Lines before filtering: 373193'
./opus_TED2020/v1.log:+ echo 'Lines after filtering: 333658'
./opus_QED/v2.0a.log:+ echo 'Lines before filtering: 487300'
./opus_QED/v2.0a.log:+ echo 'Lines after filtering: 396536'
./mtdata_JW300.log:+ echo 'Lines before filtering: 865388'
./mtdata_JW300.log:+ echo 'Lines after filtering: 764529'
./opus_Tatoeba/v2021-03-10.log:+ echo 'Lines before filtering: 512920'
./opus_Tatoeba/v2021-03-10.log:+ echo 'Lines after filtering: 486235'
./mtdata_wiki_titles_v1.log:+ echo 'Lines before filtering: 585872'
./mtdata_wiki_titles_v1.log:+ echo 'Lines after filtering: 469129'
./opus_ELRC_2922/v1.log:+ echo 'Lines before filtering: 3868'
./opus_ELRC_2922/v1.log:+ echo 'Lines after filtering: 3509'
./mtdata_neulab_tedtalksv1_train.log:+ echo 'Lines before filtering: 202473'
./mtdata_neulab_tedtalksv1_train.log:+ echo 'Lines after filtering: 181875'
./custom-corpus_/data/rw/home/corpus/ru-en/ParaCrawl-paracrawl-1_bonus-eng-rus.log:+ echo 'Lines before filtering: 4916885'
./custom-corpus_/data/rw/home/corpus/ru-en/ParaCrawl-paracrawl-1_bonus-eng-rus.log:+ echo 'Lines after filtering: 3881054'
./opus_Tanzil/v1.log:+ echo 'Lines before filtering: 887456'
./opus_Tanzil/v1.log:+ echo 'Lines after filtering: 683613'
./opus_ada83/v1.log:+ echo 'Lines before filtering: 4050'
./opus_ada83/v1.log:+ echo 'Lines after filtering: 3589'
./opus_Wikipedia/v1.0.log:+ echo 'Lines before filtering: 427786'
./opus_Wikipedia/v1.0.log:+ echo 'Lines after filtering: 333925'
./opus_KDE4/v2.log:+ echo 'Lines before filtering: 114288'
./opus_KDE4/v2.log:+ echo 'Lines after filtering: 86665'
./mtdata_worldbank.log:+ echo 'Lines before filtering: 25278'
./mtdata_worldbank.log:+ echo 'Lines after filtering: 24270'
./opus_WikiMatrix/v1.log:+ echo 'Lines before filtering: 1520248'
./opus_WikiMatrix/v1.log:+ echo 'Lines after filtering: 1309019'
./opus_GNOME/v1.log:+ echo 'Lines before filtering: 103'
./opus_GNOME/v1.log:+ echo 'Lines after filtering: 86'
./opus_UN/v20090831.log:+ echo 'Lines before filtering: 69518'
./opus_UN/v20090831.log:+ echo 'Lines after filtering: 64088'
./opus_bible-uedin/v1.log:+ echo 'Lines before filtering: 60980'
./opus_bible-uedin/v1.log:+ echo 'Lines after filtering: 39845'
./mtdata_wiki_titles_v2.log:+ echo 'Lines before filtering: 630623'
./mtdata_wiki_titles_v2.log:+ echo 'Lines after filtering: 506045'
./opus_TildeMODEL/v2018.log:+ echo 'Lines before filtering: 9451'
./opus_TildeMODEL/v2018.log:+ echo 'Lines after filtering: 8289'
./mtdata_airbaltic.log:+ echo 'Lines before filtering: 1033'
./mtdata_airbaltic.log:+ echo 'Lines after filtering: 895'
```

We'll see how it affects quality. I'll retrain backward and teacher models using this corpus.

**Comment by kpu** [comment]
You still have wiki titles v1 and wiki titles v2.

**Comment by eu9ene** [comment]
I see positive results when using bicleaner-ai multilingual with `--disable_hardrules` flag.

40.57 BLEU after 2 epochs of training. Closing this issue, there is #55 to switch bicleaner to bicleaner-ai multilingual.
