### ISSUE TITLE
tedx download via sacrebleu fails due to directionality of the data set

### ISSUE THREAD

**Issue by kpu** [mozilla/firefox-translations-training#74]
When training a French system, we ran into a failed "download" by sacrebleu because the training pipeline presumes it can pass en-fr to sacrebleu when the data set is only fr-en (indicating the direction in which it was translated).  

https://github.com/mjpost/sacrebleu/issues/177

This will also impact other languages with the same data set el es it pt it ru depending on direction.

**Comment by eu9ene** [comment]
This must be a result of the recent mtdata update https://github.com/mozilla/firefox-translations-training/pull/60

**Comment by kpu** [comment]
No it's the sacrebleu importer 
https://github.com/mozilla/firefox-translations-training/blob/3b3f33bf2581238d325f05015123fc0a026c394e/pipeline/data/importers/corpus/sacrebleu.sh#L16

**Comment by gregtatum** [comment]
This looks like it's still valid. I guess we should try both directions in the pipeline script.
