### ISSUE TITLE
Teacher does not continue training after pretraining on augmented corpus

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#75]
I continue testing the pipeline and I see that almost all teacher models don't continue training even after I increased patience by setting `early-stopping: 20`. 

Currently, continuation happens by training new models on a parallel corpus using `--pretrained-model` and `model.npz.best-chrf.npz` of the teacher that was pre-trained on an augmented corpus for 2 epochs. 

Also, I see that somehow quality of every continuation model is a bit worse than for pre-trained model, and we use the continuation model for translation further in the pipeline.

I went with this approach after having constant workflow issues with continuation in the same folder.
It seems this is not correct. Maybe we should copy `model.npz.optimizer.npz`  or an entire directory instead of using the `--pretrained-model` flag? @kpu @XapaJIaMnu

**Comment by gregtatum** [comment]
@eu9ene Is this bug actionable? Should we close without more specific things to focus on?

**Comment by eu9ene** [comment]
It's essentially the same as https://github.com/mozilla/firefox-translations-training/issues/472. Now we train everything in one run with OpusTrainer and don't have a problem using the worse fine-tuned model since the pre-trained checkpoint will be used if it doesn't continue training.
