### ISSUE TITLE
Taskcluster train actions fail

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#810]
I’m trying to restart some trainings that failed with deadline exceeded and they all fail with 404 in logs. Apparently it can’t find some task. For example: https://firefox-ci-tc.services.mozilla.com/tasks/Jyi8Pmf8TZ-ve9Q8JE8RcA/runs/0

It fails for all the languages I'm trying to restart.

**Comment by eu9ene** [comment]
It's likely related to the workaround for the deadline issue: https://github.com/mozilla/firefox-translations-training/issues/691

**Comment by bhearsum** [comment]
Upstream fix is being worked on in https://github.com/taskcluster/taskgraph/pull/569

**Comment by eu9ene** [comment]
@bhearsum I see, thanks for the investigation and prioritizing this! I'd like to point out that this issue has been blocking us for two weeks and all the training in the big batch is currently stopped. I didn't want to ping other people since you have the most context on all this. I guess we'll need to figure out how to cherry pick the required fixes in release branch because we did not upgrade taskgraph there yet.

**Comment by bhearsum** [comment]
I'll see what I can do about `release`. I can probably have something up for that today or tomorrow.

**Comment by eu9ene** [comment]
The action worked with the fix: https://firefox-ci-tc.services.mozilla.com/tasks/O7cfmFR_SuaZNg8d8b0EWQ

**Comment by bhearsum** [comment]
https://github.com/mozilla/firefox-translations-training/pull/834 fixed this on main by picking up the upstream fix.
