### ISSUE TITLE
Firefox BroFirefox browser spell checker does not workwser 

### ISSUE THREAD

**Issue by OpenGreenStreet** [mozilla/firefox-translations-training#866]
I don't know if I'm in the right place:

I've been annoyed for years that the spell checker in Firefox doesn't work.
I have tried it on different PCs and with different versions. (In the settings, “Check spelling as you type” is active). Edge and Chrome underline misspellings with a red wavy line. Unfortunately nothing in Firefox . . .

**Comment by cadeyrn** [comment]
> I don't know if I'm in the right place:

No, this is neither a bugtracker for Firefox nor is this place about the spell checker. This repository / issues tracker is about "Training pipelines for Firefox Translations machine translation models" (quoted from the project README).

If you want to report bugs in Firefox, you can do it on https://bugzilla.mozilla.org/. If you need support, you can ask for help on https://support.mozilla.org/.

**Comment by OpenGreenStreet** [comment]
@cadeyrn Thank you for the tip. I will try there.
